-- Seed data for sys_providers and sys_provider_auth_modes

INSERT OR IGNORE INTO sys_providers (provider_id, provider_name, api_protocol, default_concurrency, default_timeout_sec) VALUES
-- 国际主流大厂
('openai', 'OpenAI', 'openai', 0, 120),
('anthropic', 'Anthropic', 'anthropic', 0, 120),
('google', 'Google AI Studio (原生 Gemini)', 'google', 0, 120),
('google_cloud', 'Google Agent Platform', 'google', 0, 120),
('azure', 'Microsoft Azure OpenAI', 'openai', 0, 120),
('bedrock', 'Amazon AWS Bedrock', 'openai', 0, 120),
('cohere', 'Cohere', 'openai', 0, 120),
('mistral', 'Mistral AI', 'openai', 0, 120),

-- 聚合器与云平台
('openrouter', 'OpenRouter', 'openai', 0, 120),
('siliconflow', 'SiliconFlow (硅基流动)', 'openai', 0, 120),
('groq', 'Groq (LPU)', 'openai', 0, 120),
('perplexity', 'Perplexity', 'openai', 0, 120),
('replicate', 'Replicate', 'openai', 0, 120),
('huggingface', 'HuggingFace', 'openai', 0, 120),
('fireworks', 'Fireworks AI', 'openai', 0, 120),
('cerebras', 'Cerebras', 'openai', 0, 120),

-- 中国大陆第一梯队
('deepseek', 'DeepSeek (深度求索)', 'openai', 0, 120),
('deepseek_anthropic', 'DeepSeek (Anthropic 协议)', 'anthropic', 0, 120),
('zhipu', '智谱 AI (ChatGLM)', 'openai', 0, 120),
('moonshot', '月之暗面 (Kimi)', 'openai', 0, 120),
('baichuan', '百川智能 (Baichuan)', 'openai', 0, 120),
('minimax', 'MiniMax (海螺)', 'openai', 0, 120),
('doubao', '火山引擎 (字节豆包)', 'openai', 0, 120),
('dashscope', '阿里云 (通义千问)', 'openai', 0, 120),
('qianfan', '百度智能云 (千帆/文心)', 'openai', 0, 120),
('hunyuan', '腾讯云 (混元)', 'openai', 0, 120),
('stepfun', '阶跃星辰 (StepFun)', 'openai', 0, 120),
('01ai', '零一万物 (01.AI)', 'openai', 0, 120),
('sensenova', '商汤科技 (日日新)', 'openai', 0, 120),

-- 本地部署模型
('ollama', 'Ollama (本地部署)', 'local', 0, 120),
('vllm', 'vLLM (本地部署)', 'local', 0, 120),

-- 用户请求补充的新增厂商/工具链
('cloudflare', 'Cloudflare AI Gateway', 'openai', 0, 120),
('cloudflare_workers', 'Cloudflare Workers AI', 'openai', 0, 120),
('vercel', 'Vercel AI Gateway', 'openai', 0, 120),
('litellm', 'LiteLLM', 'openai', 0, 120),
('xai', 'xAI (Grok)', 'openai', 0, 120),
('nvidia', 'NVIDIA NIM', 'openai', 0, 120),
('together', 'Together AI', 'openai', 0, 120),
('runway', 'Runway', 'openai', 0, 120),
('elevenlabs', 'ElevenLabs', 'openai', 0, 120),
('comfyui', 'ComfyUI', 'local', 0, 120),
('bedrock_mantle', 'Amazon Bedrock Mantle', 'openai', 0, 120),
('arcee', 'Arcee AI', 'openai', 0, 120),
('azure_speech', 'Azure Speech', 'openai', 0, 120),
('byteplus', 'BytePlus', 'openai', 0, 120),
('chutes', 'Chutes', 'openai', 0, 120),
('deepinfra', 'DeepInfra', 'openai', 0, 120),
('ds4', 'ds4 (local DeepSeek V4)', 'local', 0, 120),
('fal', 'fal', 'openai', 0, 120),
('github_copilot', 'GitHub Copilot', 'openai', 0, 120),
('gradium', 'Gradium', 'openai', 0, 120),
('inferrs', 'inferrs (local models)', 'local', 0, 120),
('kilocode', 'Kilocode', 'openai', 0, 120),
('lmstudio', 'LM Studio (local models)', 'local', 0, 120),
('opencode', 'OpenCode', 'openai', 0, 120),
('opencode_go', 'OpenCode Go', 'openai', 0, 120),
('opencode_zen', 'OpenCode Zen', 'openai', 0, 120),
('senseaudio', 'SenseAudio', 'openai', 0, 120),
('sglang', 'SGLang (local models)', 'local', 0, 120),
('synthetic', 'Synthetic', 'openai', 0, 120),
('venice', 'Venice AI', 'openai', 0, 120),
('vydra', 'Vydra', 'openai', 0, 120),
('xiaomi', 'Xiaomi', 'openai', 0, 120),
('xiaomi_china', 'Xiaomi MiMo Token Plan (China)', 'openai', 0, 120),
('xiaomi_amsterdam', 'Xiaomi MiMo Token Plan (Amsterdam)', 'openai', 0, 120),
('xiaomi_singapore', 'Xiaomi MiMo Token Plan (Singapore)', 'openai', 0, 120),
('zai', 'ZAI', 'openai', 0, 120),
('kimi_coding', 'Kimi For Coding', 'openai', 0, 120),

-- pi/packages/ai Providers
('amazon-bedrock', 'Amazon-Bedrock (pi)', 'openai', 0, 120),
('azure-openai-responses', 'Azure-Openai-Responses (pi)', 'openai', 0, 120),
('cloudflare-ai-gateway', 'Cloudflare-Ai-Gateway (pi)', 'openai', 0, 120),
('cloudflare-workers-ai', 'Cloudflare-Workers-Ai (pi)', 'openai', 0, 120),
('github-copilot', 'Github-Copilot (pi)', 'openai', 0, 120),
('google-vertex', 'Google-Vertex (pi)', 'openai', 0, 120),
('kimi-coding', 'Kimi-Coding (pi)', 'openai', 0, 120),
('openai-codex', 'Openai-Codex (pi)', 'openai', 0, 120),
('opencode-go', 'Opencode-Go (pi)', 'openai', 0, 120),
('vercel-ai-gateway', 'Vercel-Ai-Gateway (pi)', 'openai', 0, 120);

INSERT OR IGNORE INTO sys_provider_auth_modes (mode_id, provider_id, mode_name, auth_type, header_name, url_template, required_fields) VALUES
-- 国际大厂
('openai_bearer', 'openai', 'OpenAI API Key', 'bearer', 'Authorization', 'https://api.openai.com/v1', '["api_key"]'),
('anthropic_key', 'anthropic', 'Anthropic API Key', 'header', 'x-api-key', 'https://api.anthropic.com/v1', '["api_key"]'),
('google_key', 'google', 'Google AI Studio Key', 'query', 'key', 'https://generativelanguage.googleapis.com/v1beta', '["api_key"]'),
('google_cloud_adc', 'google_cloud', 'Google Agent Platform ADC', 'adc', 'Authorization', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', '["project_id", "region"]'),
('google_cloud_key', 'google_cloud', 'Google Agent Platform Key', 'header', 'Authorization', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', '["api_key", "project_id", "region"]'),
('azure_key', 'azure', 'Azure API Key', 'header', 'api-key', 'https://{resource}.openai.azure.com/openai', '["api_key", "resource"]'),
('bedrock_aksk', 'bedrock', 'AWS AK/SK', 'aws_sigv4', '', 'https://bedrock-runtime.{region}.amazonaws.com', '["aws_access_key", "aws_secret_key", "region"]'),
('cohere_bearer', 'cohere', 'Cohere API Key', 'bearer', 'Authorization', 'https://api.cohere.ai/v1', '["api_key"]'),
('mistral_bearer', 'mistral', 'Mistral API Key', 'bearer', 'Authorization', 'https://api.mistral.ai/v1', '["api_key"]'),

-- 聚合器与云平台
('openrouter_bearer', 'openrouter', 'OpenRouter Key', 'bearer', 'Authorization', 'https://openrouter.ai/api/v1', '["api_key"]'),
('siliconflow_bearer', 'siliconflow', 'SiliconFlow Key', 'bearer', 'Authorization', 'https://api.siliconflow.cn/v1', '["api_key"]'),
('groq_bearer', 'groq', 'Groq Key', 'bearer', 'Authorization', 'https://api.groq.com/openai/v1', '["api_key"]'),
('perplexity_bearer', 'perplexity', 'Perplexity Key', 'bearer', 'Authorization', 'https://api.perplexity.ai', '["api_key"]'),
('replicate_bearer', 'replicate', 'Replicate Key', 'bearer', 'Authorization', 'https://api.replicate.com/v1', '["api_key"]'),
('huggingface_bearer', 'huggingface', 'HuggingFace Key', 'bearer', 'Authorization', 'https://api-inference.huggingface.co/v1', '["api_key"]'),
('fireworks_bearer', 'fireworks', 'Fireworks API Key', 'bearer', 'Authorization', 'https://api.fireworks.ai/inference/v1', '["api_key"]'),
('cerebras_bearer', 'cerebras', 'Cerebras API Key', 'bearer', 'Authorization', 'https://api.cerebras.ai/v1', '["api_key"]'),

-- 中国大陆第一梯队 (全部使用 Bearer Token)
('deepseek_bearer', 'deepseek', 'DeepSeek API Key', 'bearer', 'Authorization', 'https://api.deepseek.com/v1', '["api_key"]'),
('deepseek_anthropic_key', 'deepseek_anthropic', 'DeepSeek Anthropic Key', 'header', 'x-api-key', 'https://api.deepseek.com/beta', '["api_key"]'),
('zhipu_bearer', 'zhipu', '智谱 API Key', 'bearer', 'Authorization', 'https://open.bigmodel.cn/api/paas/v4', '["api_key"]'),
('moonshot_bearer', 'moonshot', '月之暗面 API Key', 'bearer', 'Authorization', 'https://api.moonshot.cn/v1', '["api_key"]'),
('baichuan_bearer', 'baichuan', '百川 API Key', 'bearer', 'Authorization', 'https://api.baichuan-ai.com/v1', '["api_key"]'),
('minimax_bearer', 'minimax', 'MiniMax API Key', 'bearer', 'Authorization', 'https://api.minimax.chat/v1', '["api_key"]'),
('doubao_bearer', 'doubao', '火山引擎 API Key', 'bearer', 'Authorization', 'https://ark.cn-beijing.volces.com/api/v3', '["api_key"]'),
('dashscope_bearer', 'dashscope', '阿里云 API Key', 'bearer', 'Authorization', 'https://dashscope.aliyuncs.com/compatible-mode/v1', '["api_key"]'),
('qianfan_bearer', 'qianfan', '百度千帆 API Key', 'bearer', 'Authorization', 'https://qianfan.baidubce.com/v2', '["api_key"]'),
('hunyuan_bearer', 'hunyuan', '腾讯混元 API Key', 'bearer', 'Authorization', 'https://api.hunyuan.cloud.tencent.com/v1', '["api_key"]'),
('stepfun_bearer', 'stepfun', '阶跃星辰 API Key', 'bearer', 'Authorization', 'https://api.stepfun.com/v1', '["api_key"]'),
('01ai_bearer', '01ai', '零一万物 API Key', 'bearer', 'Authorization', 'https://api.lingyiwanwu.com/v1', '["api_key"]'),
('sensenova_bearer', 'sensenova', '商汤 API Key', 'bearer', 'Authorization', 'https://api.sensenova.cn/compatible-mode/v1', '["api_key"]'),

-- 本地部署
('ollama_none', 'ollama', 'Ollama 无鉴权', 'none', '', 'http://127.0.0.1:11434/v1', '[]'),
('vllm_none', 'vllm', 'vLLM 无鉴权', 'none', '', 'http://127.0.0.1:8000/v1', '[]'),

-- 用户请求补充的厂商鉴权配置
('cloudflare_bearer', 'cloudflare', 'Cloudflare Gateway Key', 'bearer', 'Authorization', 'https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/openai', '["api_key", "account_id", "gateway_id"]'),
('cloudflare_workers_bearer', 'cloudflare_workers', 'Cloudflare Workers Key', 'bearer', 'Authorization', 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1', '["api_key", "account_id"]'),
('vercel_bearer', 'vercel', 'Vercel AI Gateway Key', 'bearer', 'Authorization', 'https://api.vercel.com/v1', '["api_key"]'),
('litellm_bearer', 'litellm', 'LiteLLM Key', 'bearer', 'Authorization', 'http://127.0.0.1:4000/v1', '["api_key"]'),
('xai_bearer', 'xai', 'xAI API Key', 'bearer', 'Authorization', 'https://api.x.ai/v1', '["api_key"]'),
('nvidia_bearer', 'nvidia', 'NVIDIA NIM Key', 'bearer', 'Authorization', 'https://integrate.api.nvidia.com/v1', '["api_key"]'),
('together_bearer', 'together', 'Together AI Key', 'bearer', 'Authorization', 'https://api.together.xyz/v1', '["api_key"]'),
('runway_bearer', 'runway', 'Runway Key', 'bearer', 'Authorization', 'https://api.runwayml.com/v1', '["api_key"]'),
('elevenlabs_bearer', 'elevenlabs', 'ElevenLabs Key', 'bearer', 'Authorization', 'https://api.elevenlabs.io/v1', '["api_key"]'),
('comfyui_none', 'comfyui', 'ComfyUI (无鉴权)', 'none', '', 'http://127.0.0.1:8188', '[]'),
('bedrock_mantle_aksk', 'bedrock_mantle', 'AWS AK/SK', 'aws_sigv4', '', 'https://bedrock-runtime.{region}.amazonaws.com', '["aws_access_key", "aws_secret_key", "region"]'),
('arcee_bearer', 'arcee', 'Arcee AI Key', 'bearer', 'Authorization', 'https://api.arcee.ai/v1', '["api_key"]'),
('azure_speech_key', 'azure_speech', 'Azure Speech Key', 'header', 'Ocp-Apim-Subscription-Key', 'https://{region}.tts.speech.microsoft.com', '["api_key", "region"]'),
('byteplus_bearer', 'byteplus', 'BytePlus Key', 'bearer', 'Authorization', 'https://api.byteplus.com/v1', '["api_key"]'),
('chutes_bearer', 'chutes', 'Chutes Key', 'bearer', 'Authorization', 'https://api.chutes.ai/v1', '["api_key"]'),
('deepinfra_bearer', 'deepinfra', 'DeepInfra Key', 'bearer', 'Authorization', 'https://api.deepinfra.com/v1/openai', '["api_key"]'),
('ds4_none', 'ds4', 'ds4 (无鉴权)', 'none', '', 'http://127.0.0.1:8080/v1', '[]'),
('fal_bearer', 'fal', 'fal API Key', 'bearer', 'Authorization', 'https://api.fal.ai/v1', '["api_key"]'),
('github_copilot_bearer', 'github_copilot', 'GitHub Copilot Token', 'bearer', 'Authorization', 'https://api.githubcopilot.com', '["api_key"]'),
('gradium_bearer', 'gradium', 'Gradium Key', 'bearer', 'Authorization', 'https://api.gradium.ai/v1', '["api_key"]'),
('inferrs_none', 'inferrs', 'inferrs (无鉴权)', 'none', '', 'http://127.0.0.1:8000/v1', '[]'),
('kilocode_bearer', 'kilocode', 'Kilocode Key', 'bearer', 'Authorization', 'https://api.kilocode.com/v1', '["api_key"]'),
('lmstudio_none', 'lmstudio', 'LM Studio (无鉴权)', 'none', '', 'http://127.0.0.1:1234/v1', '[]'),
('opencode_bearer', 'opencode', 'OpenCode Key', 'bearer', 'Authorization', 'https://api.opencode.com/v1', '["api_key"]'),
('opencode_go_bearer', 'opencode_go', 'OpenCode Go Key', 'bearer', 'Authorization', 'https://api.opencode.com/go/v1', '["api_key"]'),
('opencode_zen_bearer', 'opencode_zen', 'OpenCode Zen Key', 'bearer', 'Authorization', 'https://api.opencode.com/zen/v1', '["api_key"]'),
('senseaudio_bearer', 'senseaudio', 'SenseAudio Key', 'bearer', 'Authorization', 'https://api.sensenova.cn/v1', '["api_key"]'),
('sglang_none', 'sglang', 'SGLang (无鉴权)', 'none', '', 'http://127.0.0.1:30000/v1', '[]'),
('synthetic_bearer', 'synthetic', 'Synthetic Key', 'bearer', 'Authorization', 'https://api.synthetic.ai/v1', '["api_key"]'),
('venice_bearer', 'venice', 'Venice AI Key', 'bearer', 'Authorization', 'https://api.venice.ai/api/v1', '["api_key"]'),
('vydra_bearer', 'vydra', 'Vydra Key', 'bearer', 'Authorization', 'https://api.vydra.ai/v1', '["api_key"]'),
('xiaomi_bearer', 'xiaomi', 'Xiaomi API Key', 'bearer', 'Authorization', 'https://api.xiaomi.com/v1', '["api_key"]'),
('xiaomi_china_bearer', 'xiaomi_china', 'Xiaomi MiMo (China)', 'bearer', 'Authorization', 'https://api.mimo.xiaomi.com/v1', '["api_key"]'),
('xiaomi_amsterdam_bearer', 'xiaomi_amsterdam', 'Xiaomi MiMo (Amsterdam)', 'bearer', 'Authorization', 'https://eu.api.mimo.xiaomi.com/v1', '["api_key"]'),
('xiaomi_singapore_bearer', 'xiaomi_singapore', 'Xiaomi MiMo (Singapore)', 'bearer', 'Authorization', 'https://sg.api.mimo.xiaomi.com/v1', '["api_key"]'),
('zai_bearer', 'zai', 'ZAI Key', 'bearer', 'Authorization', 'https://api.zai.com/v1', '["api_key"]'),
('kimi_coding_bearer', 'kimi_coding', 'Kimi For Coding Key', 'bearer', 'Authorization', 'https://api.moonshot.cn/v1', '["api_key"]');
