-- Migration 002: Seed Providers and Endpoints

INSERT OR IGNORE INTO sys_providers (provider_id, provider_name, description, display_order) VALUES
('deepseek', 'DeepSeek (深度求索)', NULL, 1),
('anthropic', 'Anthropic', NULL, 2),
('google', 'Google AI Studio (原生 Gemini)', NULL, 3),
('mistral', 'Mistral AI', NULL, 4),
('openai', 'OpenAI', NULL, 5),
('perplexity', 'Perplexity', NULL, 6),
('xai', 'xAI (Grok)', NULL, 7),
('01ai', '零一万物 (01.AI)', NULL, 8),
('baichuan', '百川智能 (Baichuan)', NULL, 9),
('dashscope', '阿里云 (通义千问)', NULL, 10),
('doubao', '火山引擎 (字节豆包)', NULL, 11),
('hunyuan', '腾讯云 (混元)', NULL, 12),
('minimax', 'MiniMax (海螺)', NULL, 13),
('moonshot', '月之暗面 (Kimi)', NULL, 14),
('qianfan', '百度智能云 (千帆/文心)', NULL, 15),
('sensenova', '商汤科技 (日日新)', NULL, 16),
('stepfun', '阶跃星辰 (StepFun)', NULL, 17),
('zhipu', '智谱 AI (ChatGLM)', NULL, 18),
('azure', 'Microsoft Azure OpenAI', NULL, 19),
('azure_speech', 'Azure Speech', NULL, 20),
('bedrock', 'Amazon AWS Bedrock', NULL, 21),
('byteplus', 'BytePlus', NULL, 22),
('gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform', NULL, 23),
('github_copilot', 'GitHub Copilot', NULL, 24),
('nvidia', 'NVIDIA NIM', NULL, 25),
('opencode', 'OpenCode', NULL, 26),
('ds4', 'ds4 (local DeepSeek V4)', NULL, 27),
('inferrs', 'inferrs (local models)', NULL, 28),
('lmstudio', 'LM Studio (local models)', NULL, 29),
('ollama', 'Ollama (本地部署)', NULL, 30),
('sglang', 'SGLang (local models)', NULL, 31),
('vllm', 'vLLM (本地部署)', NULL, 32),
('custom_anthropic', '自定义 (Anthropic 兼容)', NULL, 33),
('custom_google', '自定义 (Google 兼容)', NULL, 34),
('custom_openai', '自定义 (OpenAI 兼容)', NULL, 35);
;

INSERT OR IGNORE INTO sys_access_endpoints (endpoint_id, provider_id, display_name, api_protocol, default_base_url, auth_type, auth_header, required_credential_fields, display_order) VALUES
('01ai_bearer', '01ai', '零一万物 API Key', 'openai', 'https://api.lingyiwanwu.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('anthropic_key', 'anthropic', 'Anthropic API Key', 'anthropic', 'https://api.anthropic.com/v1', 'header', 'x-api-key', '["api_key"]', 0),
('azure_key', 'azure', 'Azure API Key', 'openai', 'https://{resource}.openai.azure.com/openai', 'header', 'api-key', '["api_key", "resource"]', 0),
('azure_speech_key', 'azure_speech', 'Azure Speech Key', 'openai', 'https://{region}.tts.speech.microsoft.com', 'header', 'Ocp-Apim-Subscription-Key', '["api_key", "region"]', 0),
('baichuan_bearer', 'baichuan', '百川 API Key', 'openai', 'https://api.baichuan-ai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('bedrock_aksk', 'bedrock', 'AWS AK/SK', 'openai', 'https://bedrock-runtime.{region}.amazonaws.com', 'aws_sigv4', '', '["aws_access_key", "aws_secret_key", "region"]', 0),
('bedrock_mantle_aksk', 'bedrock', 'AWS AK/SK', 'openai', 'https://bedrock-runtime.{region}.amazonaws.com', 'aws_sigv4', '', '["aws_access_key", "aws_secret_key", "region"]', 0),
('byteplus_bearer', 'byteplus', 'BytePlus Key', 'openai', 'https://api.byteplus.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('custom_anthropic_key', 'custom_anthropic', '自定义 Anthropic Key', 'anthropic', 'https://api.anthropic.com/v1', 'header', 'x-api-key', '["api_key"]', 0),
('custom_google_key', 'custom_google', '自定义 Google Key', 'google', 'https://generativelanguage.googleapis.com/v1beta', 'query', 'key', '["api_key"]', 0),
('custom_openai_bearer', 'custom_openai', '自定义 OpenAI Key', 'openai', 'https://api.openai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('dashscope_bearer', 'dashscope', '阿里云 API Key', 'openai', 'https://dashscope.aliyuncs.com/compatible-mode/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('deepseek_anthropic_key', 'deepseek', 'DeepSeek Anthropic Key', 'anthropic', 'https://api.deepseek.com/beta', 'header', 'x-api-key', '["api_key"]', 0),
('deepseek_bearer', 'deepseek', 'DeepSeek API Key', 'openai', 'https://api.deepseek.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('doubao_bearer', 'doubao', '火山引擎 API Key', 'openai', 'https://ark.cn-beijing.volces.com/api/v3', 'bearer', 'Authorization', '["api_key"]', 0),
('ds4_none', 'ds4', 'ds4 (无鉴权)', 'local', 'http://127.0.0.1:8080/v1', 'none', '', '[]', 0),
('gemini_enterprise_agent_platform_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform ADC', 'google', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_anthropic_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Anthropic ADC', 'anthropic', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_anthropic_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Anthropic Key', 'anthropic', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'header', 'Authorization', '["api_key", "project_id", "region"]', 0),
('gemini_enterprise_agent_platform_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Key', 'google', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'header', 'Authorization', '["api_key", "project_id", "region"]', 0),
('gemini_enterprise_agent_platform_openai_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform OpenAI ADC', 'openai', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}/endpoints/openapi', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_openai_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform OpenAI Key', 'openai', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}/endpoints/openapi', 'bearer', 'Authorization', '["api_key", "project_id", "region"]', 0),
('github_copilot_bearer', 'github_copilot', 'GitHub Copilot Token', 'openai', 'https://api.githubcopilot.com', 'bearer', 'Authorization', '["api_key"]', 0),
('google_key', 'google', 'Google AI Studio Key', 'google', 'https://generativelanguage.googleapis.com/v1beta', 'query', 'key', '["api_key"]', 0),
('hunyuan_bearer', 'hunyuan', '腾讯混元 API Key', 'openai', 'https://api.hunyuan.cloud.tencent.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('inferrs_none', 'inferrs', 'inferrs (无鉴权)', 'local', 'http://127.0.0.1:8000/v1', 'none', '', '[]', 0),
('kimi_coding_bearer', 'moonshot', 'Kimi For Coding Key', 'openai', 'https://api.moonshot.cn/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('lmstudio_none', 'lmstudio', 'LM Studio (无鉴权)', 'local', 'http://127.0.0.1:1234/v1', 'none', '', '[]', 0),
('minimax_bearer', 'minimax', 'MiniMax API Key', 'openai', 'https://api.minimax.chat/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('mistral_bearer', 'mistral', 'Mistral API Key', 'openai', 'https://api.mistral.ai/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('moonshot_bearer', 'moonshot', '月之暗面 API Key', 'openai', 'https://api.moonshot.cn/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('nvidia_bearer', 'nvidia', 'NVIDIA NIM Key', 'openai', 'https://integrate.api.nvidia.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('ollama_none', 'ollama', 'Ollama 无鉴权', 'local', 'http://127.0.0.1:11434/v1', 'none', '', '[]', 0),
('openai_bearer', 'openai', 'OpenAI API Key', 'openai', 'https://api.openai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_bearer', 'opencode', 'OpenCode Key', 'openai', 'https://api.opencode.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_go_bearer', 'opencode', 'OpenCode Go Key', 'openai', 'https://api.opencode.com/go/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_zen_bearer', 'opencode', 'OpenCode Zen Key', 'openai', 'https://api.opencode.com/zen/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('perplexity_bearer', 'perplexity', 'Perplexity Key', 'openai', 'https://api.perplexity.ai', 'bearer', 'Authorization', '["api_key"]', 0),
('qianfan_bearer', 'qianfan', '百度千帆 API Key', 'openai', 'https://qianfan.baidubce.com/v2', 'bearer', 'Authorization', '["api_key"]', 0),
('sensenova_bearer', 'sensenova', '商汤 API Key', 'openai', 'https://api.sensenova.cn/compatible-mode/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('sglang_none', 'sglang', 'SGLang (无鉴权)', 'local', 'http://127.0.0.1:30000/v1', 'none', '', '[]', 0),
('stepfun_bearer', 'stepfun', '阶跃星辰 API Key', 'openai', 'https://api.stepfun.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('vllm_none', 'vllm', 'vLLM 无鉴权', 'local', 'http://127.0.0.1:8000/v1', 'none', '', '[]', 0),
('xai_bearer', 'xai', 'xAI API Key', 'openai', 'https://api.x.ai/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('zhipu_bearer', 'zhipu', '智谱 API Key', 'openai', 'https://open.bigmodel.cn/api/paas/v4', 'bearer', 'Authorization', '["api_key"]', 0),

;
-- Migration 002: Seed Providers and Endpoints

INSERT OR IGNORE INTO sys_providers (provider_id, provider_name, description, display_order) VALUES
('deepseek', 'DeepSeek (深度求索)', NULL, 1),
('anthropic', 'Anthropic', NULL, 2),
('google', 'Google AI Studio (原生 Gemini)', NULL, 3),
('mistral', 'Mistral AI', NULL, 4),
('openai', 'OpenAI', NULL, 5),
('perplexity', 'Perplexity', NULL, 6),
('xai', 'xAI (Grok)', NULL, 7),
('01ai', '零一万物 (01.AI)', NULL, 8),
('baichuan', '百川智能 (Baichuan)', NULL, 9),
('dashscope', '阿里云 (通义千问)', NULL, 10),
('doubao', '火山引擎 (字节豆包)', NULL, 11),
('hunyuan', '腾讯云 (混元)', NULL, 12),
('minimax', 'MiniMax (海螺)', NULL, 13),
('moonshot', '月之暗面 (Kimi)', NULL, 14),
('qianfan', '百度智能云 (千帆/文心)', NULL, 15),
('sensenova', '商汤科技 (日日新)', NULL, 16),
('stepfun', '阶跃星辰 (StepFun)', NULL, 17),
('zhipu', '智谱 AI (ChatGLM)', NULL, 18),
('azure', 'Microsoft Azure OpenAI', NULL, 19),
('azure_speech', 'Azure Speech', NULL, 20),
('bedrock', 'Amazon AWS Bedrock', NULL, 21),
('byteplus', 'BytePlus', NULL, 22),
('gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform', NULL, 23),
('github_copilot', 'GitHub Copilot', NULL, 24),
('nvidia', 'NVIDIA NIM', NULL, 25),
('opencode', 'OpenCode', NULL, 26),
('ds4', 'ds4 (local DeepSeek V4)', NULL, 27),
('inferrs', 'inferrs (local models)', NULL, 28),
('lmstudio', 'LM Studio (local models)', NULL, 29),
('ollama', 'Ollama (本地部署)', NULL, 30),
('sglang', 'SGLang (local models)', NULL, 31),
('vllm', 'vLLM (本地部署)', NULL, 32),
('custom_anthropic', '自定义 (Anthropic 兼容)', NULL, 33),
('custom_google', '自定义 (Google 兼容)', NULL, 34),
('custom_openai', '自定义 (OpenAI 兼容)', NULL, 35);
('01ai', 'yi-large', 'yi-large'),
('01ai', 'yi-lightning', 'yi-lightning'),
('01ai', 'yi-vision', 'yi-vision'),
('anthropic', 'claude-3-5-haiku-latest', 'claude-3-5-haiku-latest'),
('anthropic', 'claude-3-7-opus-latest', 'claude-3-7-opus-latest'),
('anthropic', 'claude-3-7-sonnet-latest', 'claude-3-7-sonnet-latest'),
('anthropic', 'claude-haiku-4-5', 'claude-haiku-4-5'),
('anthropic', 'claude-haiku-4-5-20251001', 'claude-haiku-4-5-20251001'),
('anthropic', 'claude-opus-4-0', 'claude-opus-4-0'),
('anthropic', 'claude-opus-4-1', 'claude-opus-4-1'),
('anthropic', 'claude-opus-4-5', 'claude-opus-4-5'),
('anthropic', 'claude-opus-4-5-20251101', 'claude-opus-4-5-20251101'),
('anthropic', 'claude-opus-4-6', 'claude-opus-4-6'),
('anthropic', 'claude-opus-4-7', 'claude-opus-4-7'),
('anthropic', 'claude-sonnet-4-0', 'claude-sonnet-4-0'),
('anthropic', 'claude-sonnet-4-5', 'claude-sonnet-4-5'),
('anthropic', 'claude-sonnet-4-5-20250929', 'claude-sonnet-4-5-20250929'),
('anthropic', 'claude-sonnet-4-6', 'claude-sonnet-4-6'),
('azure', 'gpt-4o', 'gpt-4o'),
('azure', 'gpt-4o-mini', 'gpt-4o-mini'),
('azure', 'o1', 'o1'),
('azure', 'o1-pro', 'o1-pro'),
('azure', 'o3', 'o3'),
('azure', 'o3-mini', 'o3-mini'),
('azure', 'o3-pro', 'o3-pro'),
('azure', 'o4', 'o4'),
('azure', 'o4-mini', 'o4-mini'),
('azure', 'o4-mini-deep-research', 'o4-mini-deep-research'),
('baichuan', 'baichuan-5', 'baichuan-5'),
('bedrock', 'qwen.qwen3-coder-30b-a3b-v1:0', 'qwen.qwen3-coder-30b-a3b-v1:0'),
('bedrock', 'qwen.qwen3-coder-480b-a35b-v1:0', 'qwen.qwen3-coder-480b-a35b-v1:0'),
('byteplus', 'kimi-k2-5-260127', 'kimi-k2-5-260127'),
('byteplus', 'kimi-k2-thinking', 'kimi-k2-thinking'),
('byteplus', 'kimi-k2.5', 'kimi-k2.5'),
('dashscope', 'qwen-3-max', 'qwen-3-max'),
('dashscope', 'qwen-3-plus', 'qwen-3-plus'),
('dashscope', 'qwen-coder-plus', 'qwen-coder-plus'),
('dashscope', 'qwen3.5-flash', 'qwen3.5-flash'),
('dashscope', 'qwen3.5-plus', 'qwen3.5-plus'),
('dashscope', 'qwen3.6-27b', 'qwen3.6-27b'),
('dashscope', 'qwen3.6-flash', 'qwen3.6-flash'),
('dashscope', 'qwen3.7-max', 'qwen3.7-max'),
('doubao', 'deepseek-v3-2-251201', 'deepseek-v3-2-251201'),
('doubao', 'kimi-k2-5-260127', 'kimi-k2-5-260127'),
('doubao', 'kimi-k2-thinking', 'kimi-k2-thinking'),
('doubao', 'kimi-k2.5', 'kimi-k2.5'),
('github_copilot', 'claude-haiku-4.5', 'claude-haiku-4.5'),
('github_copilot', 'claude-opus-4.5', 'claude-opus-4.5'),
('github_copilot', 'claude-opus-4.6', 'claude-opus-4.6'),
('github_copilot', 'claude-opus-4.7', 'claude-opus-4.7'),
('github_copilot', 'claude-sonnet-4.5', 'claude-sonnet-4.5'),
('github_copilot', 'claude-sonnet-4.6', 'claude-sonnet-4.6'),
('github_copilot', 'gemini-2.5-pro', 'gemini-2.5-pro'),
('github_copilot', 'gemini-3-flash', 'gemini-3-flash'),
('github_copilot', 'gemini-3-flash-preview', 'gemini-3-flash-preview'),
('github_copilot', 'gemini-3.1-pro', 'gemini-3.1-pro'),
('github_copilot', 'gemini-3.1-pro-preview', 'gemini-3.1-pro-preview'),
('github_copilot', 'gemini-3.5-flash', 'gemini-3.5-flash'),
('google', 'gemini-2.5-flash-lite', 'gemini-2.5-flash-lite'),
('google', 'gemini-2.5-pro', 'gemini-2.5-pro'),
('google', 'gemini-3-flash-preview', 'gemini-3-flash-preview'),
('google', 'gemini-3-pro-preview', 'gemini-3-pro-preview'),
('google', 'gemini-3.0-flash', 'gemini-3.0-flash'),
('google', 'gemini-3.0-pro', 'gemini-3.0-pro'),
('google', 'gemini-3.1-flash', 'gemini-3.1-flash'),
('google', 'gemini-3.1-flash-lite', 'gemini-3.1-flash-lite'),
('google', 'gemini-3.1-flash-lite-preview', 'gemini-3.1-flash-lite-preview'),
('google', 'gemini-3.1-pro-preview', 'gemini-3.1-pro-preview'),
('google', 'gemini-3.1-pro-preview-customtools', 'gemini-3.1-pro-preview-customtools'),
('google', 'gemini-3.5-flash', 'gemini-3.5-flash'),
('gemini_enterprise_agent_platform', 'gemini-2.5-flash-lite', 'gemini-2.5-flash-lite'),
('gemini_enterprise_agent_platform', 'gemini-2.5-pro', 'gemini-2.5-pro'),
('gemini_enterprise_agent_platform', 'gemini-3-flash-preview', 'gemini-3-flash-preview'),
('gemini_enterprise_agent_platform', 'gemini-3-pro-preview', 'gemini-3-pro-preview'),
('gemini_enterprise_agent_platform', 'gemini-3.0-flash', 'gemini-3.0-flash'),
('gemini_enterprise_agent_platform', 'gemini-3.0-pro', 'gemini-3.0-pro'),
('gemini_enterprise_agent_platform', 'gemini-3.1-flash', 'gemini-3.1-flash'),
('gemini_enterprise_agent_platform', 'gemini-3.1-flash-lite', 'gemini-3.1-flash-lite'),
('gemini_enterprise_agent_platform', 'gemini-3.1-flash-lite-preview', 'gemini-3.1-flash-lite-preview'),
('gemini_enterprise_agent_platform', 'gemini-3.1-pro-preview', 'gemini-3.1-pro-preview'),
('gemini_enterprise_agent_platform', 'gemini-3.1-pro-preview-customtools', 'gemini-3.1-pro-preview-customtools'),
('gemini_enterprise_agent_platform', 'gemini-3.5-flash', 'gemini-3.5-flash'),
('moonshot', 'kimi-for-coding', 'kimi-for-coding'),
('moonshot', 'kimi-k2-thinking', 'kimi-k2-thinking'),
('moonshot', 'kimi-k2-thinking-turbo', 'kimi-k2-thinking-turbo'),
('moonshot', 'kimi-k2-turbo', 'kimi-k2-turbo'),
('moonshot', 'kimi-k2.5', 'kimi-k2.5'),
('moonshot', 'kimi-k2.5-coding', 'kimi-k2.5-coding'),
('moonshot', 'kimi-k2.6', 'kimi-k2.6'),
('moonshot', 'kimi-k2.6-coding', 'kimi-k2.6-coding'),
('moonshot', 'moonshot-v1-128k', 'moonshot-v1-128k'),
('moonshot', 'moonshot-v1-32k', 'moonshot-v1-32k'),
('moonshot', 'moonshot-v1-8k', 'moonshot-v1-8k'),
('nvidia', 'kimi-k2.5', 'kimi-k2.5'),
('ollama', 'qwen3:32b', 'qwen3:32b'),
('openai', 'gpt-4o', 'gpt-4o'),
('openai', 'gpt-4o-mini', 'gpt-4o-mini'),
('openai', 'o1', 'o1'),
('openai', 'o1-pro', 'o1-pro'),
('openai', 'o3', 'o3'),
('openai', 'o3-mini', 'o3-mini'),
('openai', 'o3-pro', 'o3-pro'),
('openai', 'o4-mini', 'o4-mini'),
('openai', 'o4-mini-deep-research', 'o4-mini-deep-research'),
('opencode', 'claude-haiku-4-5', 'claude-haiku-4-5'),
('opencode', 'claude-opus-4-1', 'claude-opus-4-1'),
('opencode', 'claude-opus-4-5', 'claude-opus-4-5'),
('opencode', 'claude-opus-4-6', 'claude-opus-4-6'),
('opencode', 'claude-sonnet-4', 'claude-sonnet-4'),
('opencode', 'claude-sonnet-4-5', 'claude-sonnet-4-5'),
('opencode', 'claude-sonnet-4-6', 'claude-sonnet-4-6'),
('opencode', 'gemini-3-flash', 'gemini-3-flash'),
('opencode', 'gemini-3.1-pro', 'gemini-3.1-pro'),
('opencode', 'gemini-3.5-flash', 'gemini-3.5-flash'),
('opencode', 'glm-5', 'glm-5'),
('opencode', 'glm-5.1', 'glm-5.1'),
('opencode', 'qwen3.5-plus', 'qwen3.5-plus'),
('opencode', 'qwen3.6-plus', 'qwen3.6-plus'),
('qianfan', 'deepseek-v3.2', 'deepseek-v3.2'),
('zhipu', 'glm-4-plus', 'glm-4-plus'),
('zhipu', 'glm-5', 'glm-5'),
('zhipu', 'glm-5.1', 'glm-5.1'),
('zhipu', 'glm-5.1-highspeed', 'glm-5.1-highspeed'),







-- Auto-generated OpenRouter Providers --
;

INSERT OR IGNORE INTO sys_access_endpoints (endpoint_id, provider_id, display_name, api_protocol, default_base_url, auth_type, auth_header, required_credential_fields, display_order) VALUES
('openai_bearer', 'openai', 'OpenAI API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('minimax_bearer', 'minimax', 'Minimax API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('stepfun_bearer', 'stepfun', 'StepFun API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('deepseek_bearer', 'deepseek', 'DeepSeek API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('perplexity_bearer', 'perplexity', 'Perplexity API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('xai_bearer', 'xai', 'xAI API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('azure_bearer', 'azure', 'Azure API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('nvidia_bearer', 'nvidia', 'Nvidia API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('mistral_bearer', 'mistral', 'Mistral API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('anthropic_bearer', 'anthropic', 'Anthropic API Key', 'openai', 'https://openrouter.ai/api/v1', 'bearer', 'Authorization', '["api_key"]', 0);
