-- Migration 002: Seed Providers and Endpoints

INSERT OR IGNORE INTO sys_providers (provider_id, provider_name, description, display_order) VALUES
('deepseek', 'DeepSeek (深度求索)', NULL, 1),
('anthropic', 'Anthropic', NULL, 2),
('google', 'Google AI Studio (原生 Gemini)', NULL, 3),
('mistral', 'Mistral AI', NULL, 4),
('openai', 'OpenAI', NULL, 5),
('perplexity', 'Perplexity', NULL, 6),
('xai', 'xAI (Grok)', NULL, 7),
('01ai', '零一万物 (01.AI)', NULL, 8),
('baichuan', '百川智能 (Baichuan)', NULL, 9),
('dashscope', '阿里云 (通义千问)', NULL, 10),
('doubao', '火山引擎 (字节豆包)', NULL, 11),
('hunyuan', '腾讯云 (混元)', NULL, 12),
('minimax', 'MiniMax (海螺)', NULL, 13),
('moonshot', '月之暗面 (Kimi)', NULL, 14),
('qianfan', '百度智能云 (千帆/文心)', NULL, 15),
('sensenova', '商汤科技 (日日新)', NULL, 16),
('stepfun', '阶跃星辰 (StepFun)', NULL, 17),
('zhipu', '智谱 AI (ChatGLM)', NULL, 18),
('azure', 'Microsoft Azure OpenAI', NULL, 19),
('azure_speech', 'Azure Speech', NULL, 20),
('bedrock', 'Amazon AWS Bedrock', NULL, 21),
('byteplus', 'BytePlus', NULL, 22),
('gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform', NULL, 23),
('github_copilot', 'GitHub Copilot', NULL, 24),
('nvidia', 'NVIDIA NIM', NULL, 25),
('opencode', 'OpenCode', NULL, 26),
('ds4', 'ds4 (local DeepSeek V4)', NULL, 27),
('inferrs', 'inferrs (local models)', NULL, 28),
('lmstudio', 'LM Studio (local models)', NULL, 29),
('ollama', 'Ollama (本地部署)', NULL, 30),
('sglang', 'SGLang (local models)', NULL, 31),
('vllm', 'vLLM (本地部署)', NULL, 32),
('custom_anthropic', '自定义 (Anthropic 兼容)', NULL, 33),
('custom_google', '自定义 (Google 兼容)', NULL, 34),
('custom_openai', '自定义 (OpenAI 兼容)', NULL, 35);
;

INSERT OR IGNORE INTO sys_access_endpoints (endpoint_id, provider_id, display_name, api_protocol, default_base_url, auth_type, auth_header, required_credential_fields, display_order) VALUES
('01ai_bearer', '01ai', '零一万物 API Key', 'openai', 'https://api.lingyiwanwu.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('anthropic_key', 'anthropic', 'Anthropic API Key', 'anthropic', 'https://api.anthropic.com/v1', 'header', 'x-api-key', '["api_key"]', 0),
('azure_key', 'azure', 'Azure API Key', 'openai', 'https://{resource}.openai.azure.com/openai', 'header', 'api-key', '["api_key", "resource"]', 0),
('azure_speech_key', 'azure_speech', 'Azure Speech Key', 'openai', 'https://{region}.tts.speech.microsoft.com', 'header', 'Ocp-Apim-Subscription-Key', '["api_key", "region"]', 0),
('baichuan_bearer', 'baichuan', '百川 API Key', 'openai', 'https://api.baichuan-ai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('bedrock_aksk', 'bedrock', 'AWS AK/SK', 'openai', 'https://bedrock-runtime.{region}.amazonaws.com', 'aws_sigv4', '', '["aws_access_key", "aws_secret_key", "region"]', 0),
('bedrock_mantle_aksk', 'bedrock', 'AWS AK/SK', 'openai', 'https://bedrock-runtime.{region}.amazonaws.com', 'aws_sigv4', '', '["aws_access_key", "aws_secret_key", "region"]', 0),
('byteplus_bearer', 'byteplus', 'BytePlus Key', 'openai', 'https://api.byteplus.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('custom_anthropic_key', 'custom_anthropic', '自定义 Anthropic Key', 'anthropic', 'https://api.anthropic.com/v1', 'header', 'x-api-key', '["api_key"]', 0),
('custom_google_key', 'custom_google', '自定义 Google Key', 'google', 'https://generativelanguage.googleapis.com/v1beta', 'query', 'key', '["api_key"]', 0),
('custom_openai_bearer', 'custom_openai', '自定义 OpenAI Key', 'openai', 'https://api.openai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('dashscope_bearer', 'dashscope', '阿里云 API Key', 'openai', 'https://dashscope.aliyuncs.com/compatible-mode/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('deepseek_anthropic_key', 'deepseek', 'DeepSeek Anthropic Key', 'anthropic', 'https://api.deepseek.com/beta', 'header', 'x-api-key', '["api_key"]', 0),
('deepseek_bearer', 'deepseek', 'DeepSeek API Key', 'openai', 'https://api.deepseek.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('doubao_bearer', 'doubao', '火山引擎 API Key', 'openai', 'https://ark.cn-beijing.volces.com/api/v3', 'bearer', 'Authorization', '["api_key"]', 0),
('ds4_none', 'ds4', 'ds4 (无鉴权)', 'local', 'http://127.0.0.1:8080/v1', 'none', '', '[]', 0),
('gemini_enterprise_agent_platform_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform ADC', 'google', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_anthropic_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Anthropic ADC', 'anthropic', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_anthropic_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Anthropic Key', 'anthropic', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'header', 'Authorization', '["api_key", "project_id", "region"]', 0),
('gemini_enterprise_agent_platform_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform Key', 'google', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}', 'header', 'Authorization', '["api_key", "project_id", "region"]', 0),
('gemini_enterprise_agent_platform_openai_adc', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform OpenAI ADC', 'openai', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}/endpoints/openapi', 'adc', 'Authorization', '["project_id", "region"]', 0),
('gemini_enterprise_agent_platform_openai_key', 'gemini_enterprise_agent_platform', 'Gemini Enterprise Agent Platform OpenAI Key', 'openai', 'https://aiplatform.googleapis.com/v1/projects/{project_id}/locations/{region}/endpoints/openapi', 'bearer', 'Authorization', '["api_key", "project_id", "region"]', 0),
('github_copilot_bearer', 'github_copilot', 'GitHub Copilot Token', 'openai', 'https://api.githubcopilot.com', 'bearer', 'Authorization', '["api_key"]', 0),
('google_key', 'google', 'Google AI Studio Key', 'google', 'https://generativelanguage.googleapis.com/v1beta', 'query', 'key', '["api_key"]', 0),
('hunyuan_bearer', 'hunyuan', '腾讯混元 API Key', 'openai', 'https://api.hunyuan.cloud.tencent.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('inferrs_none', 'inferrs', 'inferrs (无鉴权)', 'local', 'http://127.0.0.1:8000/v1', 'none', '', '[]', 0),
('kimi_coding_bearer', 'moonshot', 'Kimi For Coding Key', 'openai', 'https://api.moonshot.cn/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('lmstudio_none', 'lmstudio', 'LM Studio (无鉴权)', 'local', 'http://127.0.0.1:1234/v1', 'none', '', '[]', 0),
('minimax_bearer', 'minimax', 'MiniMax API Key', 'openai', 'https://api.minimax.chat/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('mistral_bearer', 'mistral', 'Mistral API Key', 'openai', 'https://api.mistral.ai/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('moonshot_bearer', 'moonshot', '月之暗面 API Key', 'openai', 'https://api.moonshot.cn/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('nvidia_bearer', 'nvidia', 'NVIDIA NIM Key', 'openai', 'https://integrate.api.nvidia.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('ollama_none', 'ollama', 'Ollama 无鉴权', 'local', 'http://127.0.0.1:11434/v1', 'none', '', '[]', 0),
('openai_bearer', 'openai', 'OpenAI API Key', 'openai', 'https://api.openai.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_bearer', 'opencode', 'OpenCode Key', 'openai', 'https://api.opencode.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_go_bearer', 'opencode', 'OpenCode Go Key', 'openai', 'https://api.opencode.com/go/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('opencode_zen_bearer', 'opencode', 'OpenCode Zen Key', 'openai', 'https://api.opencode.com/zen/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('perplexity_bearer', 'perplexity', 'Perplexity Key', 'openai', 'https://api.perplexity.ai', 'bearer', 'Authorization', '["api_key"]', 0),
('qianfan_bearer', 'qianfan', '百度千帆 API Key', 'openai', 'https://qianfan.baidubce.com/v2', 'bearer', 'Authorization', '["api_key"]', 0),
('sensenova_bearer', 'sensenova', '商汤 API Key', 'openai', 'https://api.sensenova.cn/compatible-mode/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('sglang_none', 'sglang', 'SGLang (无鉴权)', 'local', 'http://127.0.0.1:30000/v1', 'none', '', '[]', 0),
('stepfun_bearer', 'stepfun', '阶跃星辰 API Key', 'openai', 'https://api.stepfun.com/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('vllm_none', 'vllm', 'vLLM 无鉴权', 'local', 'http://127.0.0.1:8000/v1', 'none', '', '[]', 0),
('xai_bearer', 'xai', 'xAI API Key', 'openai', 'https://api.x.ai/v1', 'bearer', 'Authorization', '["api_key"]', 0),
('zhipu_bearer', 'zhipu', '智谱 API Key', 'openai', 'https://open.bigmodel.cn/api/paas/v4', 'bearer', 'Authorization', '["api_key"]', 0),

;
