-- Seed data for sys_models (Built-in standard models mapping)

INSERT OR IGNORE INTO sys_models (provider_id, actual_model_id, display_name) VALUES
-- Anthropic
('anthropic', 'claude-opus-4-7', 'Claude Opus 4.7 (Claude CLI)'),
('anthropic', 'claude-sonnet-4-6', 'Claude Sonnet 4.6 (Claude CLI)'),
('anthropic', 'claude-opus-4-6', 'Claude Opus 4.6 (Claude CLI)'),
('anthropic', 'claude-3-7-sonnet-latest', 'Claude 3.7 Sonnet'),
('anthropic', 'claude-3-7-opus-latest', 'Claude 3.7 Opus'),

-- Google
('google', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview'),
('google', 'gemini-2.5-pro', 'Gemini 2.5 Pro'),
('google', 'gemini-3.1-flash', 'Gemini 3.1 Flash'),
('google', 'gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite'),
('google', 'gemma-4', 'Gemma 4'),
('google', 'gemini-3.0-pro', 'Gemini 3.0 Pro'),
('google', 'gemini-3.0-flash', 'Gemini 3.0 Flash'),

-- Google Cloud (Agent Platform)
('google_cloud', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro (GCP)'),
('google_cloud', 'gemini-2.5-pro', 'Gemini 2.5 Pro (GCP)'),
('google_cloud', 'gemini-3.1-flash', 'Gemini 3.1 Flash (GCP)'),

-- Azure OpenAI
('azure', 'gpt-5.5', 'Azure GPT-5.5'),
('azure', 'gpt-5.4-mini', 'Azure GPT-5.4 Mini'),
('azure', 'o4', 'Azure o4'),
('azure', 'o3-mini', 'Azure o3-mini'),

-- AWS Bedrock
('bedrock', 'anthropic.claude-3-7-sonnet', 'Claude 3.7 Sonnet (Bedrock)'),
('bedrock', 'meta.llama-4-70b-instruct', 'Llama 4 70B (Bedrock)'),
('bedrock', 'amazon.nova-pro-latest', 'Nova Pro (Bedrock)'),

-- Cohere
('cohere', 'command-r-plus', 'Command R+'),
('cohere', 'command-r7', 'Command R7'),

-- OpenAI
('openai', 'gpt-5.3-chat-latest', 'GPT-5.3 Chat (latest)'),
('openai', 'gpt-5.3-codex', 'GPT-5.3 Codex'),
('openai', 'gpt-5.4', 'GPT-5.4'),
('openai', 'gpt-5.4-mini', 'GPT-5.4 mini'),
('openai', 'gpt-5.4-nano', 'GPT-5.4 nano'),
('openai', 'gpt-5.4-pro', 'GPT-5.4 Pro'),
('openai', 'gpt-5.5', 'GPT-5.5'),
('openai', 'gpt-5.5-pro', 'GPT-5.5 Pro'),
('openai', 'o1', 'o1'),
('openai', 'o1-pro', 'o1-pro'),
('openai', 'o3', 'o3'),
('openai', 'o3-deep-research', 'o3-deep-research'),
('openai', 'o3-mini', 'o3-mini'),
('openai', 'o3-pro', 'o3-pro'),
('openai', 'o4-mini', 'o4-mini'),
('openai', 'o4-mini-deep-research', 'o4-mini-deep-research'),

-- xAI (Grok)
('xai', 'grok-beta', 'Grok Beta'),
('xai', 'grok-2', 'Grok 2'),
('xai', 'grok-3', 'Grok 3'),

-- BytePlus
('byteplus', 'seed-1-8-251228', 'Seed 1.8'),
('byteplus', 'kimi-k2-5-260127', 'Kimi K2.5'),
('byteplus', 'glm-4-7-251222', 'GLM 4.7'),
('byteplus', 'ark-code-latest', 'Ark Coding Plan'),
('byteplus', 'doubao-seed-code', 'Doubao Seed Code'),
('byteplus', 'glm-4.7', 'GLM 4.7 Coding'),
('byteplus', 'kimi-k2-thinking', 'Kimi K2 Thinking'),
('byteplus', 'kimi-k2.5', 'Kimi K2.5 Coding'),

-- Cerebras
('cerebras', 'zai-glm-4.7', 'Z.ai GLM 4.7'),
('cerebras', 'gpt-oss-120b', 'GPT OSS 120B'),
('cerebras', 'qwen-3-235b-a22b-instruct-2507', 'Qwen 3 235B Instruct'),
('cerebras', 'llama3.1-8b', 'Llama 3.1 8B'),

-- Chutes
('chutes', 'Qwen/Qwen3-32B', 'Qwen/Qwen3-32B'),
('chutes', 'unsloth/Mistral-Nemo-Instruct-2407', 'unsloth/Mistral-Nemo-Instruct-2407'),
('chutes', 'deepseek-ai/DeepSeek-V3-0324-TEE', 'deepseek-ai/DeepSeek-V3-0324-TEE'),
('chutes', 'Qwen/Qwen3-235B-A22B-Instruct-2507-TEE', 'Qwen/Qwen3-235B-A22B-Instruct-2507-TEE'),
('chutes', 'openai/gpt-oss-120b-TEE', 'openai/gpt-oss-120b-TEE'),
('chutes', 'chutesai/Mistral-Small-3.1-24B-Instruct-2503', 'chutesai/Mistral-Small-3.1-24B-Instruct-2503'),
('chutes', 'deepseek-ai/DeepSeek-V3.2-TEE', 'deepseek-ai/DeepSeek-V3.2-TEE'),
('chutes', 'zai-org/GLM-4.7-TEE', 'zai-org/GLM-4.7-TEE'),
('chutes', 'moonshotai/Kimi-K2.5-TEE', 'moonshotai/Kimi-K2.5-TEE'),
('chutes', 'unsloth/gemma-3-27b-it', 'unsloth/gemma-3-27b-it'),
('chutes', 'XiaomiMiMo/MiMo-V2-Flash-TEE', 'XiaomiMiMo/MiMo-V2-Flash-TEE'),
('chutes', 'chutesai/Mistral-Small-3.2-24B-Instruct-2506', 'chutesai/Mistral-Small-3.2-24B-Instruct-2506'),
('chutes', 'deepseek-ai/DeepSeek-R1-0528-TEE', 'deepseek-ai/DeepSeek-R1-0528-TEE'),
('chutes', 'zai-org/GLM-5-TEE', 'zai-org/GLM-5-TEE'),
('chutes', 'deepseek-ai/DeepSeek-V3.1-TEE', 'deepseek-ai/DeepSeek-V3.1-TEE'),
('chutes', 'deepseek-ai/DeepSeek-V3.1-Terminus-TEE', 'deepseek-ai/DeepSeek-V3.1-Terminus-TEE'),
('chutes', 'unsloth/gemma-3-4b-it', 'unsloth/gemma-3-4b-it'),
('chutes', 'MiniMaxAI/MiniMax-M2.5-TEE', 'MiniMaxAI/MiniMax-M2.5-TEE'),
('chutes', 'tngtech/DeepSeek-TNG-R1T2-Chimera', 'tngtech/DeepSeek-TNG-R1T2-Chimera'),
('chutes', 'Qwen/Qwen3-Coder-Next-TEE', 'Qwen/Qwen3-Coder-Next-TEE'),
('chutes', 'NousResearch/Hermes-4-405B-FP8-TEE', 'NousResearch/Hermes-4-405B-FP8-TEE'),
('chutes', 'deepseek-ai/DeepSeek-V3', 'deepseek-ai/DeepSeek-V3'),
('chutes', 'openai/gpt-oss-20b', 'openai/gpt-oss-20b'),
('chutes', 'unsloth/Llama-3.2-3B-Instruct', 'unsloth/Llama-3.2-3B-Instruct'),
('chutes', 'unsloth/Mistral-Small-24B-Instruct-2501', 'unsloth/Mistral-Small-24B-Instruct-2501'),
('chutes', 'zai-org/GLM-4.7-FP8', 'zai-org/GLM-4.7-FP8'),
('chutes', 'zai-org/GLM-4.6-TEE', 'zai-org/GLM-4.6-TEE'),
('chutes', 'Qwen/Qwen3.5-397B-A17B-TEE', 'Qwen/Qwen3.5-397B-A17B-TEE'),
('chutes', 'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen2.5-72B-Instruct'),
('chutes', 'NousResearch/DeepHermes-3-Mistral-24B-Preview', 'NousResearch/DeepHermes-3-Mistral-24B-Preview'),
('chutes', 'Qwen/Qwen3-Next-80B-A3B-Instruct', 'Qwen/Qwen3-Next-80B-A3B-Instruct'),
('chutes', 'zai-org/GLM-4.6-FP8', 'zai-org/GLM-4.6-FP8'),
('chutes', 'Qwen/Qwen3-235B-A22B-Thinking-2507', 'Qwen/Qwen3-235B-A22B-Thinking-2507'),
('chutes', 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B', 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B'),
('chutes', 'tngtech/R1T2-Chimera-Speed', 'tngtech/R1T2-Chimera-Speed'),
('chutes', 'zai-org/GLM-4.6V', 'zai-org/GLM-4.6V'),
('chutes', 'Qwen/Qwen2.5-VL-32B-Instruct', 'Qwen/Qwen2.5-VL-32B-Instruct'),
('chutes', 'Qwen/Qwen3-VL-235B-A22B-Instruct', 'Qwen/Qwen3-VL-235B-A22B-Instruct'),
('chutes', 'Qwen/Qwen3-14B', 'Qwen/Qwen3-14B'),
('chutes', 'Qwen/Qwen2.5-Coder-32B-Instruct', 'Qwen/Qwen2.5-Coder-32B-Instruct'),
('chutes', 'Qwen/Qwen3-30B-A3B', 'Qwen/Qwen3-30B-A3B'),
('chutes', 'unsloth/gemma-3-12b-it', 'unsloth/gemma-3-12b-it'),
('chutes', 'unsloth/Llama-3.2-1B-Instruct', 'unsloth/Llama-3.2-1B-Instruct'),
('chutes', 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE', 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE'),
('chutes', 'NousResearch/Hermes-4-14B', 'NousResearch/Hermes-4-14B'),
('chutes', 'Qwen/Qwen3Guard-Gen-0.6B', 'Qwen/Qwen3Guard-Gen-0.6B'),
('chutes', 'rednote-hilab/dots.ocr', 'rednote-hilab/dots.ocr'),

-- DeepInfra
('deepinfra', 'deepseek-ai/DeepSeek-V3.2', 'DeepSeek V3.2'),
('deepinfra', 'zai-org/GLM-5.1', 'GLM-5.1'),
('deepinfra', 'stepfun-ai/Step-3.5-Flash', 'Step 3.5 Flash'),
('deepinfra', 'MiniMaxAI/MiniMax-M2.5', 'MiniMax M2.5'),
('deepinfra', 'moonshotai/Kimi-K2.5', 'Kimi K2.5'),
('deepinfra', 'nvidia/NVIDIA-Nemotron-3-Super-120B-A12B', 'NVIDIA Nemotron 3 Super 120B A12B'),
('deepinfra', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'Llama 3.3 70B Instruct Turbo'),

-- DeepSeek
('deepseek', 'deepseek-v4-flash', 'DeepSeek V4 Flash'),
('deepseek', 'deepseek-v4-pro', 'DeepSeek V4 Pro'),
('deepseek', 'deepseek-chat', 'DeepSeek Chat'),
('deepseek', 'deepseek-reasoner', 'DeepSeek Reasoner'),
('deepseek_anthropic', 'deepseek-reasoner', 'DeepSeek Reasoner (Anthropic)'),

-- Fireworks
('fireworks', 'accounts/fireworks/models/kimi-k2p6', 'Kimi K2.6'),
('fireworks', 'accounts/fireworks/routers/kimi-k2p5-turbo', 'Kimi K2.5 Turbo (Fire Pass)'),

-- Copilot
('github_copilot', 'claude-opus-4.6', 'Claude Opus 4.6'),
('github_copilot', 'claude-opus-4.7', 'Claude Opus 4.7'),
('github_copilot', 'claude-sonnet-4.6', 'Claude Sonnet 4.6'),
('github_copilot', 'gemini-2.5-pro', 'Gemini 2.5 Pro'),
('github_copilot', 'gemini-3-flash', 'Gemini 3 Flash'),
('github_copilot', 'gemini-3.1-pro', 'Gemini 3.1 Pro'),
('github_copilot', 'gpt-5.3-codex', 'GPT-5.3-Codex'),
('github_copilot', 'gpt-5.4', 'GPT-5.4'),
('github_copilot', 'gpt-5.5', 'GPT-5.5'),
('github_copilot', 'gpt-5.4-mini', 'GPT-5.4 mini'),
('github_copilot', 'gpt-5.4-nano', 'GPT-5.4 nano'),
('github_copilot', 'raptor-mini', 'Raptor mini'),
('github_copilot', 'goldeneye', 'Goldeneye'),

-- groq
('groq', 'groq/compound', 'Compound'),
('groq', 'groq/compound-mini', 'Compound Mini'),
('groq', 'llama-3.1-8b-instant', 'Llama 3.1 8B Instant'),
('groq', 'llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile'),
('groq', 'meta-llama/llama-4-scout-17b-16e-instruct', 'Llama 4 Scout 17B'),
('groq', 'openai/gpt-oss-120b', 'GPT OSS 120B'),
('groq', 'openai/gpt-oss-20b', 'GPT OSS 20B'),
('groq', 'openai/gpt-oss-safeguard-20b', 'Safety GPT OSS 20B'),
('groq', 'qwen/qwen3-32b', 'Qwen3 32B'),

-- Kilo Gateway
('kilocode', 'kilo/auto', 'Kilo Auto'),

-- Mistral AI
('mistral', 'codestral-latest', 'Codestral (latest)'),
('mistral', 'devstral-medium-latest', 'Devstral 2 (latest)'),
('mistral', 'magistral-small', 'Magistral Small'),
('mistral', 'mistral-large-latest', 'Mistral Large (latest)'),
('mistral', 'mistral-medium-2508', 'Mistral Medium 3.1'),
('mistral', 'mistral-medium-3-5', 'Mistral Medium 3.5'),
('mistral', 'mistral-small-latest', 'Mistral Small (latest)'),
('mistral', 'pixtral-large-latest', 'Pixtral Large (latest)'),

-- Moonshot AI
('moonshot', 'kimi-k2.6', 'Kimi K2.6'),
('moonshot', 'kimi-k2.5', 'Kimi K2.5'),
('moonshot', 'kimi-k2-thinking', 'Kimi K2 Thinking'),
('moonshot', 'kimi-k2-thinking-turbo', 'Kimi K2 Thinking Turbo'),
('moonshot', 'kimi-k2-turbo', 'Kimi K2 Turbo'),

-- NVIDIA
('nvidia', 'nvidia/nemotron-3-super-120b-a12b', 'NVIDIA Nemotron 3 Super 120B'),
('nvidia', 'moonshotai/kimi-k2.5', 'Kimi K2.5'),
('nvidia', 'minimaxai/minimax-m2.5', 'MiniMax M2.5'),
('nvidia', 'z-ai/glm5', 'GLM-5'),

-- OpenCode
('opencode', 'deepseek-v4-pro', 'DeepSeek V4 Pro'),
('opencode', 'deepseek-v4-flash', 'DeepSeek V4 Flash'),

-- Qianfan
('qianfan', 'deepseek-v3.2', 'DEEPSEEK V3.2'),
('qianfan', 'ernie-5.0-thinking-preview', 'ERNIE-5.0-Thinking-Preview'),

-- StepFun
('stepfun', 'step-3.5-flash', 'Step 3.5 Flash'),
('stepfun', 'step-3.5-flash-2603', 'Step 3.5 Flash 2603'),

-- Tencent Cloud
('hunyuan', 'hy3-preview', 'Hy3 preview (TokenHub)'),

-- Together AI
('together', 'zai-org/GLM-4.7', 'GLM 4.7 Fp8'),
('together', 'moonshotai/Kimi-K2.5', 'Kimi K2.5'),
('together', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'Llama 3.3 70B Instruct Turbo'),
('together', 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'Llama 4 Scout 17B 16E Instruct'),
('together', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'Llama 4 Maverick 17B 128E Instruct FP8'),
('together', 'deepseek-ai/DeepSeek-V3.1', 'DeepSeek V3.1'),
('together', 'deepseek-ai/DeepSeek-R1', 'DeepSeek R1'),
('together', 'moonshotai/Kimi-K2-Instruct-0905', 'Kimi K2-Instruct 0905'),

-- Venice AI
('venice', 'llama-3.3-70b', 'Llama 3.3 70B'),
('venice', 'llama-3.2-3b', 'Llama 3.2 3B'),
('venice', 'hermes-3-llama-3.1-405b', 'Hermes 3 Llama 3.1 405B'),
('venice', 'qwen3-235b-a22b-thinking-2507', 'Qwen3 235B Thinking'),
('venice', 'qwen3-235b-a22b-instruct-2507', 'Qwen3 235B Instruct'),
('venice', 'qwen3-coder-480b-a35b-instruct', 'Qwen3 Coder 480B'),
('venice', 'qwen3-coder-480b-a35b-instruct-turbo', 'Qwen3 Coder 480B Turbo'),
('venice', 'qwen3-5-35b-a3b', 'Qwen3.5 35B A3B'),
('venice', 'qwen3-next-80b', 'Qwen3 Next 80B'),
('venice', 'qwen3-vl-235b-a22b', 'Qwen3 VL 235B (Vision)'),
('venice', 'qwen3-4b', 'Venice Small (Qwen3 4B)'),
('venice', 'deepseek-v3.2', 'DeepSeek V3.2'),
('venice', 'venice-uncensored', 'Venice Uncensored (Dolphin-Mistral)'),
('venice', 'mistral-31-24b', 'Venice Medium (Mistral)'),
('venice', 'google-gemma-3-27b-it', 'Google Gemma 3 27B Instruct'),
('venice', 'openai-gpt-oss-120b', 'OpenAI GPT OSS 120B'),
('venice', 'nvidia-nemotron-3-nano-30b-a3b', 'NVIDIA Nemotron 3 Nano 30B'),
('venice', 'olafangensan-glm-4.7-flash-heretic', 'GLM 4.7 Flash Heretic'),
('venice', 'zai-org-glm-4.6', 'GLM 4.6'),
('venice', 'zai-org-glm-4.7', 'GLM 4.7'),
('venice', 'zai-org-glm-4.7-flash', 'GLM 4.7 Flash'),
('venice', 'zai-org-glm-5', 'GLM 5'),
('venice', 'kimi-k2-5', 'Kimi K2.5'),
('venice', 'kimi-k2-thinking', 'Kimi K2 Thinking'),
('venice', 'minimax-m21', 'MiniMax M2.1'),
('venice', 'minimax-m25', 'MiniMax M2.5'),
('venice', 'claude-opus-4-6', 'Claude Opus 4.6 (via Venice)'),
('venice', 'claude-sonnet-4-6', 'Claude Sonnet 4.6 (via Venice)'),
('venice', 'openai-gpt-52', 'GPT-5.2 (via Venice)'),
('venice', 'openai-gpt-52-codex', 'GPT-5.2 Codex (via Venice)'),
('venice', 'openai-gpt-53-codex', 'GPT-5.3 Codex (via Venice)'),
('venice', 'openai-gpt-54', 'GPT-5.4 (via Venice)'),
('venice', 'openai-gpt-4o-2024-11-20', 'GPT-4o (via Venice)'),
('venice', 'openai-gpt-4o-mini-2024-07-18', 'GPT-4o Mini (via Venice)'),
('venice', 'gemini-3-pro-preview', 'Gemini 3 Pro (via Venice)'),
('venice', 'gemini-3-1-pro-preview', 'Gemini 3.1 Pro (via Venice)'),
('venice', 'gemini-3-flash-preview', 'Gemini 3 Flash (via Venice)'),
('venice', 'grok-41-fast', 'Grok 4.1 Fast (via Venice)'),

-- Volcano Engine (doubao)
('doubao', 'doubao-seed-code-preview-251028', 'Doubao Seed Code Preview'),
('doubao', 'doubao-seed-1-8-251228', 'Doubao Seed 1.8'),
('doubao', 'kimi-k2-5-260127', 'Kimi K2.5'),
('doubao', 'glm-4-7-251222', 'GLM 4.7'),
('doubao', 'deepseek-v3-2-251201', 'DeepSeek V3.2'),
('doubao', 'ark-code-latest', 'Ark Coding Plan'),
('doubao', 'doubao-seed-code', 'Doubao Seed Code'),
('doubao', 'glm-4.7', 'GLM 4.7 Coding'),
('doubao', 'kimi-k2-thinking', 'Kimi K2 Thinking'),
('doubao', 'kimi-k2.5', 'Kimi K2.5 Coding'),

-- Xiaomi
('xiaomi', 'mimo-v2-flash', 'Xiaomi MiMo V2 Flash'),
('xiaomi', 'mimo-v2-pro', 'Xiaomi MiMo V2 Pro'),
('xiaomi', 'mimo-v2-omni', 'Xiaomi MiMo V2 Omni'),

-- Z.AI
('zai', 'glm-5.1', 'GLM-5.1'),
('zai', 'glm-5', 'GLM-5'),
('zai', 'glm-5-turbo', 'GLM-5 Turbo'),
('zai', 'glm-5v-turbo', 'GLM-5V Turbo'),
('zai', 'glm-4.7', 'GLM-4.7'),
('zai', 'glm-4.7-flash', 'GLM-4.7 Flash'),
('zai', 'glm-4.7-flashx', 'GLM-4.7 FlashX'),
('zai', 'glm-4.6', 'GLM-4.6'),
('zai', 'glm-4.6v', 'GLM-4.6V'),
('zai', 'glm-4.5', 'GLM-4.5'),
('zai', 'glm-4.5-air', 'GLM-4.5 Air'),
('zai', 'glm-4.5-flash', 'GLM-4.5 Flash'),
('zai', 'glm-4.5v', 'GLM-4.5V'),

-- Local / Open Source Additions
('ollama', 'llama4:70b', 'Llama 4 70B (Ollama)'),
('ollama', 'qwen3:32b', 'Qwen 3 32B (Ollama)'),
('ollama', 'deepseek-r2:32b', 'DeepSeek R2 32B (Ollama)'),
('vllm', 'Qwen/Qwen-3-72B-Instruct', 'Qwen 3 72B (vLLM)'),
('vllm', 'meta-llama/Llama-4-8B-Instruct', 'Llama 4 8B (vLLM)'),

-- Perplexity
('perplexity', 'sonar-pro', 'Sonar Pro'),
('perplexity', 'sonar-reasoning', 'Sonar Reasoning'),

-- Replicate
('replicate', 'meta/llama-4-70b-instruct', 'Llama 4 70B'),
('replicate', 'meta/llama-4-8b-instruct', 'Llama 4 8B'),

-- HuggingFace
('huggingface', 'meta-llama/Meta-Llama-4-70B-Instruct', 'Llama 4 70B Instruct'),

-- SiliconFlow
('siliconflow', 'deepseek-ai/DeepSeek-V4', 'DeepSeek V4 (SF)'),
('siliconflow', 'THUDM/glm-5', 'GLM-5 (SF)'),

-- OpenRouter
('openrouter', 'anthropic/claude-3.7-sonnet', 'Claude 3.7 Sonnet (OR)'),
('openrouter', 'openai/gpt-5.5', 'GPT-5.5 (OR)'),
('openrouter', 'openai/o4', 'o4 (OR)'),
('openrouter', 'google/gemini-3.1-pro', 'Gemini 3.1 Pro (OR)'),

-- Zhipu
('zhipu', 'glm-5', 'GLM-5'),
('zhipu', 'glm-5.1', 'GLM-5.1'),
('zhipu', 'glm-4-plus', 'GLM-4 Plus'),

-- Dashscope
('dashscope', 'qwen-3-max', 'Qwen 3 Max'),
('dashscope', 'qwen-3-plus', 'Qwen 3 Plus'),
('dashscope', 'qwen-coder-plus', 'Qwen Coder Plus'),

-- Baichuan
('baichuan', 'baichuan-5', 'Baichuan 5'),

-- 01.AI
('01ai', 'yi-lightning', 'Yi Lightning'),

-- SenseNova
('sensenova', 'sensenova-6.0', 'SenseNova 6.0'),

-- CC-Switch Sync Additions
('minimax', 'MiniMax-M2.7', 'MiniMax M2.7'),
('qianfan', 'qianfan-code-latest', 'Qianfan Code Latest'),
('doubao', 'doubao-seed-2-0-code-preview-latest', 'Doubao Seed 2.0 Code Preview'),
('openrouter', 'anthropic/claude-haiku-4-5', 'Claude Haiku 4.5 (OR)'),
('openrouter', 'anthropic/claude-sonnet-4-6', 'Claude Sonnet 4.6 (OR)'),
('openrouter', 'anthropic/claude-opus-4-7', 'Claude Opus 4.7 (OR)'),
('openrouter', 'google/gemini-3-pro', 'Gemini 3 Pro (OR)'),
('anthropic', 'claude-sonnet-4-5-20250929', 'Claude Sonnet 4.5'),
('anthropic', 'claude-opus-4-5-20251101', 'Claude Opus 4.5'),
('anthropic', 'claude-haiku-4-5-20251001', 'Claude Haiku 4.5'),
('anthropic', 'gemini-claude-opus-4-5-thinking', 'Antigravity - Claude Opus 4.5'),
('anthropic', 'gemini-claude-sonnet-4-5-thinking', 'Antigravity - Claude Sonnet 4.5'),
('google', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview'),
('google', 'gemini-3-pro-preview', 'Gemini 3 Pro Preview'),
('google', 'gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite'),
('bedrock', 'us.meta.llama4-maverick-17b-instruct-v1:0', 'Llama 4 Maverick 17B (Bedrock)'),
('bedrock', 'us.deepseek.r1-v1:0', 'DeepSeek R1 (Bedrock)'),

-- New comprehensive models search 2026
('dashscope', 'qwen3.7-max', 'Qwen 3.7 Max'),
('dashscope', 'qwen3.6-27b', 'Qwen 3.6 27B'),
('dashscope', 'qwen3.6-flash', 'Qwen 3.6 Flash'),
('dashscope', 'qwq-32b', 'QwQ 32B'),
('dashscope', 'qwen3.5-plus', 'Qwen 3.5 Plus'),
('dashscope', 'qwen3.5-flash', 'Qwen 3.5 Flash'),
('zhipu', 'glm-5.1-highspeed', 'GLM 5.1 Highspeed'),
('baichuan', 'Baichuan-M3-235B', 'Baichuan M3 235B'),
('baichuan', 'Baichuan-M2-32B', 'Baichuan M2 32B'),
('baichuan', 'Baichuan-M1-14B', 'Baichuan M1 14B'),
('baichuan', 'Baichuan-Omni-1.5', 'Baichuan Omni 1.5'),
('minimax', 'MiniMax-M2.7-highspeed', 'MiniMax M2.7 Highspeed'),
('minimax', 'MiniMax-M2.5-highspeed', 'MiniMax M2.5 Highspeed'),
('minimax', 'MiniMax-M2.1', 'MiniMax M2.1'),
('moonshot', 'moonshot-v1-8k', 'Moonshot V1 8K'),
('moonshot', 'moonshot-v1-32k', 'Moonshot V1 32K'),
('moonshot', 'moonshot-v1-128k', 'Moonshot V1 128K'),
('sensenova', 'sensenova-6.0-pro', 'SenseNova 6.0 Pro'),
('sensenova', 'sensenova-6.0-flash', 'SenseNova 6.0 Flash'),
('01ai', 'yi-large', 'Yi Large'),
('01ai', 'yi-vision', 'Yi Vision'),
('cloudflare', 'openai/gpt-4o', 'GPT-4o (Cloudflare Gateway)'),
('cloudflare', 'anthropic/claude-3.5-sonnet', 'Claude 3.5 Sonnet (Cloudflare)'),
('cloudflare_workers', '@cf/meta/llama-3-8b-instruct', 'Llama 3 8B (CF Workers)'),
('cloudflare_workers', '@cf/mistral/mistral-7b-instruct-v0.1', 'Mistral 7B (CF Workers)'),
('cloudflare_workers', '@cf/google/gemma-7b-it', 'Gemma 7B (CF Workers)'),
('vercel', 'openai/gpt-4o', 'GPT-4o (Vercel Gateway)'),
('vercel', 'anthropic/claude-3-5-sonnet', 'Claude 3.5 Sonnet (Vercel Gateway)'),
('litellm', 'gpt-4o', 'GPT-4o (LiteLLM)'),
('litellm', 'claude-3-5-sonnet', 'Claude 3.5 Sonnet (LiteLLM)'),
('runway', 'gen3-alpha', 'Runway Gen-3 Alpha'),
('runway', 'gen2', 'Runway Gen-2'),
('elevenlabs', 'eleven_multilingual_v2', 'ElevenLabs Multilingual V2'),
('elevenlabs', 'eleven_turbo_v2', 'ElevenLabs Turbo V2'),
('comfyui', 'comfyui-default', 'ComfyUI Default Endpoint'),
('bedrock_mantle', 'anthropic.claude-3-5-sonnet', 'Claude 3.5 Sonnet (Mantle)'),
('bedrock_mantle', 'amazon.nova-pro-latest', 'Nova Pro (Mantle)'),
('arcee', 'arcee-spark', 'Arcee Spark'),
('arcee', 'arcee-lite', 'Arcee Lite'),
('arcee', 'arcee-agent', 'Arcee Agent'),
('azure_speech', 'en-US-JennyNeural', 'Azure Speech (en-US-Jenny)'),
('azure_speech', 'zh-CN-XiaoxiaoNeural', 'Azure Speech (zh-CN-Xiaoxiao)'),
('ds4', 'deepseek-v4', 'DeepSeek V4 (Local ds4)'),
('fal', 'fal-ai/flux-pro', 'Flux Pro (fal)'),
('fal', 'fal-ai/flux-realism', 'Flux Realism (fal)'),
('fal', 'fal-ai/aura-flow', 'Aura Flow (fal)'),
('gradium', 'gradium-v1', 'Gradium V1'),
('inferrs', 'inferrs-local', 'Inferrs Local Models'),
('lmstudio', 'lmstudio-local', 'LM Studio Local'),
('opencode_go', 'opencode-go-latest', 'OpenCode Go Latest'),
('opencode_zen', 'opencode-zen-latest', 'OpenCode Zen Latest'),
('senseaudio', 'sensevoice-v1', 'SenseVoice V1'),
('sglang', 'sglang-local', 'SGLang Local Node'),
('synthetic', 'synthetic-v1', 'Synthetic V1'),
('vydra', 'vydra-v1', 'Vydra V1'),
('xiaomi_china', 'mimo-v2-flash-cn', 'MiMo V2 Flash (China)'),
('xiaomi_amsterdam', 'mimo-v2-flash-eu', 'MiMo V2 Flash (EU)'),
('xiaomi_singapore', 'mimo-v2-flash-sg', 'MiMo V2 Flash (SG)'),
('kimi_coding', 'kimi-k2.5-coding', 'Kimi K2.5 Coding Mode'),
('kimi_coding', 'kimi-k2.6-coding', 'Kimi K2.6 Coding Mode'),

-- Models Extracted from hermes-agent plugins
('vllm', 'Qwen/Qwen3.5-72B-Instruct', 'Qwen 3.5 72B Instruct'),
('openrouter', 'deepseek/deepseek-chat', 'DeepSeek Chat (OR)'),
('openrouter', 'deepseek/deepseek-r1-0528', 'DeepSeek R1 0528 (OR)'),
('openrouter', 'deepseek/deepseek-v3-0324', 'DeepSeek V3 0324 (OR)'),
('zhipu', 'glm-4-9b', 'GLM 4 9B'),
('kilocode', 'google/gemini-3-flash', 'Gemini 3 Flash (Kilocode)'),
('kilocode', 'google/gemini-3-flash-preview', 'Gemini 3 Flash Preview (Kilocode)'),
('venice', 'hermes-3-405b', 'Hermes 3 405B (Venice)'),
('venice', 'hermes-3-70b', 'Hermes 3 70B (Venice)'),
('openrouter', 'minimax/minimax-m2.7', 'MiniMax M2.7 (OR)'),
('together', 'moonshotai/kimi-k2.5', 'Kimi K2.5 (Together)'),
('nvidia', 'nvidia/llama-3.1-nemotron-70b-instruct', 'Llama 3.1 Nemotron 70B Instruct'),
('nvidia', 'nvidia/llama-3.3-70b-instruct', 'Llama 3.3 70B Instruct'),
('openrouter', 'openai/gpt-5.4', 'GPT-5.4 (OR)'),
('openrouter', 'openrouter/pareto-code', 'Pareto Code (OR)'),
('openrouter', 'qwen/qwen3-235b-a22b-fp8', 'Qwen3 235B FP8 (OR)'),
('openrouter', 'qwen/qwen3-plus', 'Qwen 3 Plus (OR)'),
('together', 'zai-org/GLM-5.1-FP8', 'GLM 5.1 FP8 (Together)'),
('together', 'zai-org/glm-5', 'GLM 5 (Together)'),

-- pi/packages/ai Models
('amazon-bedrock', 'amazon.nova-lite-v1:0', 'Amazon.Nova Lite V1:0 (pi)'),
('amazon-bedrock', 'amazon.nova-micro-v1:0', 'Amazon.Nova Micro V1:0 (pi)'),
('amazon-bedrock', 'amazon.nova-pro-v1:0', 'Amazon.Nova Pro V1:0 (pi)'),
('amazon-bedrock', 'anthropic.claude-opus-4-6-v1', 'Anthropic.Claude Opus 4 6 V1 (pi)'),
('amazon-bedrock', 'anthropic.claude-sonnet-4-6', 'Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'au.anthropic.claude-opus-4-6-v1', 'Au.Anthropic.Claude Opus 4 6 V1 (pi)'),
('amazon-bedrock', 'au.anthropic.claude-sonnet-4-6', 'Au.Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'deepseek.r1-v1:0', 'Deepseek.R1 V1:0 (pi)'),
('amazon-bedrock', 'deepseek.v3-v1:0', 'Deepseek.V3 V1:0 (pi)'),
('amazon-bedrock', 'eu.anthropic.claude-opus-4-6-v1', 'Eu.Anthropic.Claude Opus 4 6 V1 (pi)'),
('amazon-bedrock', 'eu.anthropic.claude-sonnet-4-6', 'Eu.Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'global.anthropic.claude-opus-4-6-v1', 'Global.Anthropic.Claude Opus 4 6 V1 (pi)'),
('amazon-bedrock', 'global.anthropic.claude-sonnet-4-6', 'Global.Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'google.gemma-3-4b-it', 'Google.Gemma 3 4B It (pi)'),
('amazon-bedrock', 'jp.anthropic.claude-sonnet-4-6', 'Jp.Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'meta.llama3-1-8b-instruct-v1:0', 'Meta.Llama3 1 8B Instruct V1:0 (pi)'),
('amazon-bedrock', 'mistral.ministral-3-14b-instruct', 'Mistral.Ministral 3 14B Instruct (pi)'),
('amazon-bedrock', 'mistral.ministral-3-3b-instruct', 'Mistral.Ministral 3 3B Instruct (pi)'),
('amazon-bedrock', 'mistral.ministral-3-8b-instruct', 'Mistral.Ministral 3 8B Instruct (pi)'),
('amazon-bedrock', 'nvidia.nemotron-nano-3-30b', 'Nvidia.Nemotron Nano 3 30B (pi)'),
('amazon-bedrock', 'qwen.qwen3-coder-30b-a3b-v1:0', 'Qwen.Qwen3 Coder 30B A3B V1:0 (pi)'),
('amazon-bedrock', 'qwen.qwen3-coder-480b-a35b-v1:0', 'Qwen.Qwen3 Coder 480B A35B V1:0 (pi)'),
('amazon-bedrock', 'us.anthropic.claude-opus-4-6-v1', 'Us.Anthropic.Claude Opus 4 6 V1 (pi)'),
('amazon-bedrock', 'us.anthropic.claude-sonnet-4-6', 'Us.Anthropic.Claude Sonnet 4 6 (pi)'),
('amazon-bedrock', 'us.deepseek.r1-v1:0', 'Us.Deepseek.R1 V1:0 (pi)'),
('amazon-bedrock', 'zai.glm-5', 'Zai.Glm 5 (pi)'),
('anthropic', 'claude-3-5-haiku-latest', 'Claude 3 5 Haiku Latest (pi)'),
('anthropic', 'claude-haiku-4-5', 'Claude Haiku 4 5 (pi)'),
('anthropic', 'claude-opus-4-0', 'Claude Opus 4 0 (pi)'),
('anthropic', 'claude-opus-4-1', 'Claude Opus 4 1 (pi)'),
('anthropic', 'claude-opus-4-5', 'Claude Opus 4 5 (pi)'),
('anthropic', 'claude-sonnet-4-0', 'Claude Sonnet 4 0 (pi)'),
('anthropic', 'claude-sonnet-4-5', 'Claude Sonnet 4 5 (pi)'),
('azure-openai-responses', 'gpt-4', 'Gpt 4 (pi)'),
('azure-openai-responses', 'gpt-4-turbo', 'Gpt 4 Turbo (pi)'),
('azure-openai-responses', 'gpt-4.1', 'Gpt 4.1 (pi)'),
('azure-openai-responses', 'gpt-4.1-mini', 'Gpt 4.1 Mini (pi)'),
('azure-openai-responses', 'gpt-4.1-nano', 'Gpt 4.1 Nano (pi)'),
('azure-openai-responses', 'gpt-4o', 'Gpt 4O (pi)'),
('azure-openai-responses', 'gpt-4o-mini', 'Gpt 4O Mini (pi)'),
('azure-openai-responses', 'gpt-5', 'Gpt 5 (pi)'),
('azure-openai-responses', 'gpt-5-chat-latest', 'Gpt 5 Chat Latest (pi)'),
('azure-openai-responses', 'gpt-5-mini', 'Gpt 5 Mini (pi)'),
('azure-openai-responses', 'gpt-5-nano', 'Gpt 5 Nano (pi)'),
('azure-openai-responses', 'gpt-5-pro', 'Gpt 5 Pro (pi)'),
('azure-openai-responses', 'gpt-5.1', 'Gpt 5.1 (pi)'),
('azure-openai-responses', 'gpt-5.1-chat-latest', 'Gpt 5.1 Chat Latest (pi)'),
('azure-openai-responses', 'gpt-5.3-chat-latest', 'Gpt 5.3 Chat Latest (pi)'),
('azure-openai-responses', 'gpt-5.4', 'Gpt 5.4 (pi)'),
('azure-openai-responses', 'gpt-5.4-mini', 'Gpt 5.4 Mini (pi)'),
('azure-openai-responses', 'gpt-5.4-nano', 'Gpt 5.4 Nano (pi)'),
('azure-openai-responses', 'gpt-5.4-pro', 'Gpt 5.4 Pro (pi)'),
('azure-openai-responses', 'gpt-5.5', 'Gpt 5.5 (pi)'),
('azure-openai-responses', 'gpt-5.5-pro', 'Gpt 5.5 Pro (pi)'),
('azure-openai-responses', 'o1', 'O1 (pi)'),
('azure-openai-responses', 'o1-pro', 'O1 Pro (pi)'),
('azure-openai-responses', 'o3', 'O3 (pi)'),
('azure-openai-responses', 'o3-deep-research', 'O3 Deep Research (pi)'),
('azure-openai-responses', 'o3-mini', 'O3 Mini (pi)'),
('azure-openai-responses', 'o3-pro', 'O3 Pro (pi)'),
('azure-openai-responses', 'o4-mini', 'O4 Mini (pi)'),
('azure-openai-responses', 'o4-mini-deep-research', 'O4 Mini Deep Research (pi)'),
('cloudflare-ai-gateway', 'claude-3-5-haiku', 'Claude 3 5 Haiku (pi)'),
('cloudflare-ai-gateway', 'claude-3-haiku', 'Claude 3 Haiku (pi)'),
('cloudflare-ai-gateway', 'claude-3-opus', 'Claude 3 Opus (pi)'),
('cloudflare-ai-gateway', 'claude-3-sonnet', 'Claude 3 Sonnet (pi)'),
('cloudflare-ai-gateway', 'claude-3.5-haiku', 'Claude 3.5 Haiku (pi)'),
('cloudflare-ai-gateway', 'claude-3.5-sonnet', 'Claude 3.5 Sonnet (pi)'),
('cloudflare-ai-gateway', 'claude-haiku-4-5', 'Claude Haiku 4 5 (pi)'),
('cloudflare-ai-gateway', 'claude-opus-4', 'Claude Opus 4 (pi)'),
('cloudflare-ai-gateway', 'claude-opus-4-1', 'Claude Opus 4 1 (pi)'),
('cloudflare-ai-gateway', 'claude-opus-4-5', 'Claude Opus 4 5 (pi)'),
('cloudflare-ai-gateway', 'claude-opus-4-6', 'Claude Opus 4 6 (pi)'),
('cloudflare-ai-gateway', 'claude-sonnet-4', 'Claude Sonnet 4 (pi)'),
('cloudflare-ai-gateway', 'claude-sonnet-4-5', 'Claude Sonnet 4 5 (pi)'),
('cloudflare-ai-gateway', 'claude-sonnet-4-6', 'Claude Sonnet 4 6 (pi)'),
('cloudflare-ai-gateway', 'gpt-4', 'Gpt 4 (pi)'),
('cloudflare-ai-gateway', 'gpt-4-turbo', 'Gpt 4 Turbo (pi)'),
('cloudflare-ai-gateway', 'gpt-4o', 'Gpt 4O (pi)'),
('cloudflare-ai-gateway', 'gpt-4o-mini', 'Gpt 4O Mini (pi)'),
('cloudflare-ai-gateway', 'gpt-5.1', 'Gpt 5.1 (pi)'),
('cloudflare-ai-gateway', 'gpt-5.4', 'Gpt 5.4 (pi)'),
('cloudflare-ai-gateway', 'gpt-5.5', 'Gpt 5.5 (pi)'),
('cloudflare-ai-gateway', 'o1', 'O1 (pi)'),
('cloudflare-ai-gateway', 'o3', 'O3 (pi)'),
('cloudflare-ai-gateway', 'o3-mini', 'O3 Mini (pi)'),
('cloudflare-ai-gateway', 'o3-pro', 'O3 Pro (pi)'),
('cloudflare-ai-gateway', 'o4-mini', 'O4 Mini (pi)'),
('cloudflare-workers-ai', '@cf/ibm-granite/granite-4.0-h-micro', '@Cf/Ibm Granite/Granite 4.0 H Micro (pi)'),
('cloudflare-workers-ai', '@cf/qwen/qwen3-30b-a3b-fp8', '@Cf/Qwen/Qwen3 30B A3B Fp8 (pi)'),
('fireworks', 'accounts/fireworks/models/deepseek-v4-flash', 'Accounts/Fireworks/Models/Deepseek V4 Flash (pi)'),
('fireworks', 'accounts/fireworks/models/deepseek-v4-pro', 'Accounts/Fireworks/Models/Deepseek V4 Pro (pi)'),
('fireworks', 'accounts/fireworks/models/glm-5p1', 'Accounts/Fireworks/Models/Glm 5P1 (pi)'),
('fireworks', 'accounts/fireworks/models/qwen3p6-plus', 'Accounts/Fireworks/Models/Qwen3P6 Plus (pi)'),
('fireworks', 'accounts/fireworks/routers/glm-5p1-fast', 'Accounts/Fireworks/Routers/Glm 5P1 Fast (pi)'),
('github-copilot', 'claude-haiku-4.5', 'Claude Haiku 4.5 (pi)'),
('github-copilot', 'claude-opus-4.5', 'Claude Opus 4.5 (pi)'),
('github-copilot', 'claude-opus-4.6', 'Claude Opus 4.6 (pi)'),
('github-copilot', 'claude-sonnet-4.5', 'Claude Sonnet 4.5 (pi)'),
('github-copilot', 'claude-sonnet-4.6', 'Claude Sonnet 4.6 (pi)'),
('github-copilot', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (pi)'),
('github-copilot', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview (pi)'),
('github-copilot', 'gemini-3.5-flash', 'Gemini 3.5 Flash (pi)'),
('github-copilot', 'gpt-4.1', 'Gpt 4.1 (pi)'),
('github-copilot', 'gpt-4o', 'Gpt 4O (pi)'),
('github-copilot', 'gpt-5-mini', 'Gpt 5 Mini (pi)'),
('github-copilot', 'gpt-5.4', 'Gpt 5.4 (pi)'),
('github-copilot', 'gpt-5.4-mini', 'Gpt 5.4 Mini (pi)'),
('github-copilot', 'gpt-5.5', 'Gpt 5.5 (pi)'),
('github-copilot', 'grok-code-fast-1', 'Grok Code Fast 1 (pi)'),
('google', 'gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview (pi)'),
('google', 'gemini-3.1-pro-preview-customtools', 'Gemini 3.1 Pro Preview Customtools (pi)'),
('google', 'gemini-3.5-flash', 'Gemini 3.5 Flash (pi)'),
('google', 'gemini-flash-latest', 'Gemini Flash Latest (pi)'),
('google', 'gemini-flash-lite-latest', 'Gemini Flash Lite Latest (pi)'),
('google', 'gemma-4-31b-it', 'Gemma 4 31B It (pi)'),
('google-vertex', 'gemini-1.5-flash', 'Gemini 1.5 Flash (pi)'),
('google-vertex', 'gemini-1.5-flash-8b', 'Gemini 1.5 Flash 8B (pi)'),
('google-vertex', 'gemini-1.5-pro', 'Gemini 1.5 Pro (pi)'),
('google-vertex', 'gemini-3-flash-preview', 'Gemini 3 Flash Preview (pi)'),
('google-vertex', 'gemini-3-pro-preview', 'Gemini 3 Pro Preview (pi)'),
('google-vertex', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview (pi)'),
('google-vertex', 'gemini-3.1-pro-preview-customtools', 'Gemini 3.1 Pro Preview Customtools (pi)'),
('huggingface', 'Qwen/Qwen3-Coder-480B-A35B-Instruct', 'Qwen/Qwen3 Coder 480B A35B Instruct (pi)'),
('huggingface', 'deepseek-ai/DeepSeek-V4-Pro', 'Deepseek Ai/Deepseek V4 Pro (pi)'),
('huggingface', 'zai-org/GLM-5', 'Zai Org/Glm 5 (pi)'),
('huggingface', 'zai-org/GLM-5.1', 'Zai Org/Glm 5.1 (pi)'),
('kimi-coding', 'kimi-for-coding', 'Kimi For Coding (pi)'),
('mistral', 'magistral-medium-latest', 'Magistral Medium Latest (pi)'),
('mistral', 'ministral-3b-latest', 'Ministral 3B Latest (pi)'),
('mistral', 'ministral-8b-latest', 'Ministral 8B Latest (pi)'),
('mistral', 'mistral-medium-3.5', 'Mistral Medium 3.5 (pi)'),
('mistral', 'mistral-medium-latest', 'Mistral Medium Latest (pi)'),
('mistral', 'mistral-nemo', 'Mistral Nemo (pi)'),
('openai', 'gpt-4', 'Gpt 4 (pi)'),
('openai', 'gpt-4-turbo', 'Gpt 4 Turbo (pi)'),
('openai', 'gpt-4.1', 'Gpt 4.1 (pi)'),
('openai', 'gpt-4.1-mini', 'Gpt 4.1 Mini (pi)'),
('openai', 'gpt-4.1-nano', 'Gpt 4.1 Nano (pi)'),
('openai', 'gpt-4o', 'Gpt 4O (pi)'),
('openai', 'gpt-4o-mini', 'Gpt 4O Mini (pi)'),
('openai', 'gpt-5', 'Gpt 5 (pi)'),
('openai', 'gpt-5-chat-latest', 'Gpt 5 Chat Latest (pi)'),
('openai', 'gpt-5-mini', 'Gpt 5 Mini (pi)'),
('openai', 'gpt-5-nano', 'Gpt 5 Nano (pi)'),
('openai', 'gpt-5-pro', 'Gpt 5 Pro (pi)'),
('openai', 'gpt-5.1', 'Gpt 5.1 (pi)'),
('openai', 'gpt-5.1-chat-latest', 'Gpt 5.1 Chat Latest (pi)'),
('openai-codex', 'gpt-5.4', 'Gpt 5.4 (pi)'),
('openai-codex', 'gpt-5.4-mini', 'Gpt 5.4 Mini (pi)'),
('openai-codex', 'gpt-5.5', 'Gpt 5.5 (pi)'),
('opencode', 'big-pickle', 'Big Pickle (pi)'),
('opencode', 'claude-haiku-4-5', 'Claude Haiku 4 5 (pi)'),
('opencode', 'claude-opus-4-1', 'Claude Opus 4 1 (pi)'),
('opencode', 'claude-opus-4-5', 'Claude Opus 4 5 (pi)'),
('opencode', 'claude-opus-4-6', 'Claude Opus 4 6 (pi)'),
('opencode', 'claude-sonnet-4', 'Claude Sonnet 4 (pi)'),
('opencode', 'claude-sonnet-4-5', 'Claude Sonnet 4 5 (pi)'),
('opencode', 'claude-sonnet-4-6', 'Claude Sonnet 4 6 (pi)'),
('opencode', 'deepseek-v4-flash-free', 'Deepseek V4 Flash Free (pi)'),
('opencode', 'gemini-3-flash', 'Gemini 3 Flash (pi)'),
('opencode', 'gemini-3.1-pro', 'Gemini 3.1 Pro (pi)'),
('opencode', 'gemini-3.5-flash', 'Gemini 3.5 Flash (pi)'),
('opencode', 'glm-5', 'Glm 5 (pi)'),
('opencode', 'glm-5.1', 'Glm 5.1 (pi)'),
('opencode', 'gpt-5', 'Gpt 5 (pi)'),
('opencode', 'gpt-5-nano', 'Gpt 5 Nano (pi)'),
('opencode', 'gpt-5.1', 'Gpt 5.1 (pi)'),
('opencode', 'gpt-5.4', 'Gpt 5.4 (pi)'),
('opencode', 'gpt-5.4-mini', 'Gpt 5.4 Mini (pi)'),
('opencode', 'gpt-5.4-nano', 'Gpt 5.4 Nano (pi)'),
('opencode', 'gpt-5.4-pro', 'Gpt 5.4 Pro (pi)'),
('opencode', 'gpt-5.5', 'Gpt 5.5 (pi)'),
('opencode', 'gpt-5.5-pro', 'Gpt 5.5 Pro (pi)'),
('opencode', 'grok-build-0.1', 'Grok Build 0.1 (pi)'),
('opencode', 'nemotron-3-super-free', 'Nemotron 3 Super Free (pi)'),
('opencode', 'qwen3.5-plus', 'Qwen3.5 Plus (pi)'),
('opencode', 'qwen3.6-plus', 'Qwen3.6 Plus (pi)'),
('opencode-go', 'deepseek-v4-flash', 'Deepseek V4 Flash (pi)'),
('opencode-go', 'deepseek-v4-pro', 'Deepseek V4 Pro (pi)'),
('opencode-go', 'glm-5', 'Glm 5 (pi)'),
('opencode-go', 'glm-5.1', 'Glm 5.1 (pi)'),
('opencode-go', 'qwen3.5-plus', 'Qwen3.5 Plus (pi)'),
('opencode-go', 'qwen3.6-plus', 'Qwen3.6 Plus (pi)'),
('openrouter', 'alibaba/tongyi-deepresearch-30b-a3b', 'Alibaba/Tongyi Deepresearch 30B A3B (pi)'),
('openrouter', 'amazon/nova-lite-v1', 'Amazon/Nova Lite V1 (pi)'),
('openrouter', 'amazon/nova-micro-v1', 'Amazon/Nova Micro V1 (pi)'),
('openrouter', 'amazon/nova-premier-v1', 'Amazon/Nova Premier V1 (pi)'),
('openrouter', 'amazon/nova-pro-v1', 'Amazon/Nova Pro V1 (pi)'),
('openrouter', 'anthropic/claude-3-haiku', 'Anthropic/Claude 3 Haiku (pi)'),
('openrouter', 'anthropic/claude-3.5-haiku', 'Anthropic/Claude 3.5 Haiku (pi)'),
('openrouter', 'anthropic/claude-haiku-4.5', 'Anthropic/Claude Haiku 4.5 (pi)'),
('openrouter', 'anthropic/claude-opus-4', 'Anthropic/Claude Opus 4 (pi)'),
('openrouter', 'anthropic/claude-opus-4.1', 'Anthropic/Claude Opus 4.1 (pi)'),
('openrouter', 'anthropic/claude-opus-4.5', 'Anthropic/Claude Opus 4.5 (pi)'),
('openrouter', 'anthropic/claude-opus-4.6', 'Anthropic/Claude Opus 4.6 (pi)'),
('openrouter', 'anthropic/claude-opus-4.6-fast', 'Anthropic/Claude Opus 4.6 Fast (pi)'),
('openrouter', 'anthropic/claude-sonnet-4', 'Anthropic/Claude Sonnet 4 (pi)'),
('openrouter', 'anthropic/claude-sonnet-4.5', 'Anthropic/Claude Sonnet 4.5 (pi)'),
('openrouter', 'anthropic/claude-sonnet-4.6', 'Anthropic/Claude Sonnet 4.6 (pi)'),
('openrouter', 'arcee-ai/trinity-large-thinking', 'Arcee Ai/Trinity Large Thinking (pi)'),
('openrouter', 'arcee-ai/trinity-large-thinking:free', 'Arcee Ai/Trinity Large Thinking:Free (pi)'),
('openrouter', 'arcee-ai/trinity-mini', 'Arcee Ai/Trinity Mini (pi)'),
('openrouter', 'arcee-ai/virtuoso-large', 'Arcee Ai/Virtuoso Large (pi)'),
('openrouter', 'auto', 'Auto (pi)'),
('openrouter', 'baidu/cobuddy:free', 'Baidu/Cobuddy:Free (pi)'),
('openrouter', 'bytedance-seed/seed-1.6', 'Bytedance Seed/Seed 1.6 (pi)'),
('openrouter', 'bytedance-seed/seed-1.6-flash', 'Bytedance Seed/Seed 1.6 Flash (pi)'),
('openrouter', 'deepseek/deepseek-chat-v3.1', 'Deepseek/Deepseek Chat V3.1 (pi)'),
('openrouter', 'deepseek/deepseek-r1', 'Deepseek/Deepseek R1 (pi)'),
('openrouter', 'deepseek/deepseek-v3.1-terminus', 'Deepseek/Deepseek V3.1 Terminus (pi)'),
('openrouter', 'deepseek/deepseek-v4-flash', 'Deepseek/Deepseek V4 Flash (pi)'),
('openrouter', 'deepseek/deepseek-v4-flash:free', 'Deepseek/Deepseek V4 Flash:Free (pi)'),
('openrouter', 'deepseek/deepseek-v4-pro', 'Deepseek/Deepseek V4 Pro (pi)'),
('openrouter', 'essentialai/rnj-1-instruct', 'Essentialai/Rnj 1 Instruct (pi)'),
('openrouter', 'google/gemini-3-flash-preview', 'Google/Gemini 3 Flash Preview (pi)'),
('openrouter', 'google/gemini-3.1-flash-lite', 'Google/Gemini 3.1 Flash Lite (pi)'),
('openrouter', 'google/gemini-3.1-flash-lite-preview', 'Google/Gemini 3.1 Flash Lite Preview (pi)'),
('openrouter', 'google/gemini-3.1-pro-preview', 'Google/Gemini 3.1 Pro Preview (pi)'),
('openrouter', 'google/gemini-3.1-pro-preview-customtools', 'Google/Gemini 3.1 Pro Preview Customtools (pi)'),
('openrouter', 'google/gemini-3.5-flash', 'Google/Gemini 3.5 Flash (pi)'),
('openrouter', 'google/gemma-4-31b-it', 'Google/Gemma 4 31B It (pi)'),
('openrouter', 'google/gemma-4-31b-it:free', 'Google/Gemma 4 31B It:Free (pi)'),
('openrouter', 'ibm-granite/granite-4.1-8b', 'Ibm Granite/Granite 4.1 8B (pi)'),
('openrouter', 'meta-llama/llama-3.1-8b-instruct', 'Meta Llama/Llama 3.1 8B Instruct (pi)'),
('openrouter', 'meta-llama/llama-4-scout', 'Meta Llama/Llama 4 Scout (pi)'),
('openrouter', 'mistralai/devstral-medium', 'Mistralai/Devstral Medium (pi)'),
('openrouter', 'mistralai/devstral-small', 'Mistralai/Devstral Small (pi)'),
('openrouter', 'mistralai/mistral-large', 'Mistralai/Mistral Large (pi)'),
('openrouter', 'mistralai/mistral-medium-3', 'Mistralai/Mistral Medium 3 (pi)'),
('openrouter', 'mistralai/mistral-medium-3-5', 'Mistralai/Mistral Medium 3 5 (pi)'),
('openrouter', 'mistralai/mistral-medium-3.1', 'Mistralai/Mistral Medium 3.1 (pi)'),
('openrouter', 'mistralai/mistral-nemo', 'Mistralai/Mistral Nemo (pi)'),
('openrouter', 'mistralai/mistral-saba', 'Mistralai/Mistral Saba (pi)'),
('openrouter', 'nvidia/llama-3.3-nemotron-super-49b-v1.5', 'Nvidia/Llama 3.3 Nemotron Super 49B V1.5 (pi)'),
('openrouter', 'nvidia/nemotron-3-nano-30b-a3b', 'Nvidia/Nemotron 3 Nano 30B A3B (pi)'),
('openrouter', 'nvidia/nemotron-3-nano-30b-a3b:free', 'Nvidia/Nemotron 3 Nano 30B A3B:Free (pi)'),
('openrouter', 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free', 'Nvidia/Nemotron 3 Nano Omni 30B A3B Reasoning:Free (pi)'),
('openrouter', 'openai/gpt-3.5-turbo', 'Openai/Gpt 3.5 Turbo (pi)'),
('openrouter', 'openai/gpt-3.5-turbo-0613', 'Openai/Gpt 3.5 Turbo 0613 (pi)'),
('openrouter', 'openai/gpt-3.5-turbo-16k', 'Openai/Gpt 3.5 Turbo 16K (pi)'),
('openrouter', 'openai/gpt-4', 'Openai/Gpt 4 (pi)'),
('openrouter', 'openai/gpt-4-0314', 'Openai/Gpt 4 0314 (pi)'),
('openrouter', 'openai/gpt-4-1106-preview', 'Openai/Gpt 4 1106 Preview (pi)'),
('openrouter', 'openai/gpt-4-turbo', 'Openai/Gpt 4 Turbo (pi)'),
('openrouter', 'openai/gpt-4-turbo-preview', 'Openai/Gpt 4 Turbo Preview (pi)'),
('openrouter', 'openai/gpt-4.1', 'Openai/Gpt 4.1 (pi)'),
('openrouter', 'openai/gpt-4.1-mini', 'Openai/Gpt 4.1 Mini (pi)'),
('openrouter', 'openai/gpt-4.1-nano', 'Openai/Gpt 4.1 Nano (pi)'),
('openrouter', 'openai/gpt-4o', 'Openai/Gpt 4O (pi)'),
('openrouter', 'openai/gpt-4o-audio-preview', 'Openai/Gpt 4O Audio Preview (pi)'),
('openrouter', 'openai/gpt-4o-mini', 'Openai/Gpt 4O Mini (pi)'),
('openrouter', 'openai/gpt-5', 'Openai/Gpt 5 (pi)'),
('openrouter', 'openai/gpt-5-mini', 'Openai/Gpt 5 Mini (pi)'),
('openrouter', 'openai/gpt-5-nano', 'Openai/Gpt 5 Nano (pi)'),
('openrouter', 'openai/gpt-5-pro', 'Openai/Gpt 5 Pro (pi)'),
('openrouter', 'openai/gpt-5.1', 'Openai/Gpt 5.1 (pi)'),
('openrouter', 'openai/gpt-5.1-chat', 'Openai/Gpt 5.1 Chat (pi)'),
('openrouter', 'openai/gpt-5.3-chat', 'Openai/Gpt 5.3 Chat (pi)'),
('openrouter', 'openai/gpt-5.4-mini', 'Openai/Gpt 5.4 Mini (pi)'),
('openrouter', 'openai/gpt-5.4-nano', 'Openai/Gpt 5.4 Nano (pi)'),
('openrouter', 'openai/gpt-5.4-pro', 'Openai/Gpt 5.4 Pro (pi)'),
('openrouter', 'openai/gpt-5.5-pro', 'Openai/Gpt 5.5 Pro (pi)'),
('openrouter', 'openai/gpt-audio', 'Openai/Gpt Audio (pi)'),
('openrouter', 'openai/gpt-audio-mini', 'Openai/Gpt Audio Mini (pi)'),
('openrouter', 'openai/gpt-chat-latest', 'Openai/Gpt Chat Latest (pi)'),
('openrouter', 'openai/o1', 'Openai/O1 (pi)'),
('openrouter', 'openai/o3', 'Openai/O3 (pi)'),
('openrouter', 'openai/o3-deep-research', 'Openai/O3 Deep Research (pi)'),
('openrouter', 'openai/o3-mini', 'Openai/O3 Mini (pi)'),
('openrouter', 'openai/o3-mini-high', 'Openai/O3 Mini High (pi)'),
('openrouter', 'openai/o3-pro', 'Openai/O3 Pro (pi)'),
('openrouter', 'openai/o4-mini', 'Openai/O4 Mini (pi)'),
('openrouter', 'openai/o4-mini-deep-research', 'Openai/O4 Mini Deep Research (pi)'),
('openrouter', 'openai/o4-mini-high', 'Openai/O4 Mini High (pi)'),
('openrouter', 'openrouter/auto', 'Openrouter/Auto (pi)'),
('openrouter', 'openrouter/free', 'Openrouter/Free (pi)'),
('openrouter', 'openrouter/owl-alpha', 'Openrouter/Owl Alpha (pi)'),
('openrouter', 'poolside/laguna-m.1:free', 'Poolside/Laguna M.1:Free (pi)'),
('openrouter', 'prime-intellect/intellect-3', 'Prime Intellect/Intellect 3 (pi)'),
('openrouter', 'qwen/qwen-plus', 'Qwen/Qwen Plus (pi)'),
('openrouter', 'qwen/qwen3-14b', 'Qwen/Qwen3 14B (pi)'),
('openrouter', 'qwen/qwen3-30b-a3b', 'Qwen/Qwen3 30B A3B (pi)'),
('openrouter', 'qwen/qwen3-8b', 'Qwen/Qwen3 8B (pi)'),
('openrouter', 'qwen/qwen3-coder', 'Qwen/Qwen3 Coder (pi)'),
('openrouter', 'qwen/qwen3-coder-30b-a3b-instruct', 'Qwen/Qwen3 Coder 30B A3B Instruct (pi)'),
('openrouter', 'qwen/qwen3-coder-flash', 'Qwen/Qwen3 Coder Flash (pi)'),
('openrouter', 'qwen/qwen3-coder-plus', 'Qwen/Qwen3 Coder Plus (pi)'),
('openrouter', 'qwen/qwen3-coder:free', 'Qwen/Qwen3 Coder:Free (pi)'),
('openrouter', 'qwen/qwen3-vl-30b-a3b-instruct', 'Qwen/Qwen3 Vl 30B A3B Instruct (pi)'),
('openrouter', 'qwen/qwen3-vl-30b-a3b-thinking', 'Qwen/Qwen3 Vl 30B A3B Thinking (pi)'),
('openrouter', 'qwen/qwen3-vl-8b-instruct', 'Qwen/Qwen3 Vl 8B Instruct (pi)'),
('openrouter', 'qwen/qwen3-vl-8b-thinking', 'Qwen/Qwen3 Vl 8B Thinking (pi)'),
('openrouter', 'qwen/qwen3.5-35b-a3b', 'Qwen/Qwen3.5 35B A3B (pi)'),
('openrouter', 'qwen/qwen3.5-9b', 'Qwen/Qwen3.5 9B (pi)'),
('openrouter', 'qwen/qwen3.6-35b-a3b', 'Qwen/Qwen3.6 35B A3B (pi)'),
('openrouter', 'qwen/qwen3.6-flash', 'Qwen/Qwen3.6 Flash (pi)'),
('openrouter', 'qwen/qwen3.6-plus', 'Qwen/Qwen3.6 Plus (pi)'),
('openrouter', 'rekaai/reka-edge', 'Rekaai/Reka Edge (pi)'),
('openrouter', 'relace/relace-search', 'Relace/Relace Search (pi)'),
('openrouter', 'stepfun/step-3.5-flash', 'Stepfun/Step 3.5 Flash (pi)'),
('openrouter', 'tencent/hy3-preview', 'Tencent/Hy3 Preview (pi)'),
('openrouter', 'upstage/solar-pro-3', 'Upstage/Solar Pro 3 (pi)'),
('openrouter', 'z-ai/glm-4.5', 'Z Ai/Glm 4.5 (pi)'),
('openrouter', 'z-ai/glm-4.5-air', 'Z Ai/Glm 4.5 Air (pi)'),
('openrouter', 'z-ai/glm-4.5-air:free', 'Z Ai/Glm 4.5 Air:Free (pi)'),
('openrouter', 'z-ai/glm-4.5v', 'Z Ai/Glm 4.5V (pi)'),
('openrouter', 'z-ai/glm-4.6', 'Z Ai/Glm 4.6 (pi)'),
('openrouter', 'z-ai/glm-4.6v', 'Z Ai/Glm 4.6V (pi)'),
('openrouter', 'z-ai/glm-5', 'Z Ai/Glm 5 (pi)'),
('openrouter', 'z-ai/glm-5-turbo', 'Z Ai/Glm 5 Turbo (pi)'),
('openrouter', 'z-ai/glm-5.1', 'Z Ai/Glm 5.1 (pi)'),
('openrouter', 'z-ai/glm-5v-turbo', 'Z Ai/Glm 5V Turbo (pi)'),
('openrouter', '~anthropic/claude-haiku-latest', '~Anthropic/Claude Haiku Latest (pi)'),
('openrouter', '~anthropic/claude-opus-latest', '~Anthropic/Claude Opus Latest (pi)'),
('openrouter', '~anthropic/claude-sonnet-latest', '~Anthropic/Claude Sonnet Latest (pi)'),
('openrouter', '~google/gemini-flash-latest', '~Google/Gemini Flash Latest (pi)'),
('openrouter', '~google/gemini-pro-latest', '~Google/Gemini Pro Latest (pi)'),
('openrouter', '~moonshotai/kimi-latest', '~Moonshotai/Kimi Latest (pi)'),
('openrouter', '~openai/gpt-latest', '~Openai/Gpt Latest (pi)'),
('openrouter', '~openai/gpt-mini-latest', '~Openai/Gpt Mini Latest (pi)'),
('together', 'Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8', 'Qwen/Qwen3 Coder 480B A35B Instruct Fp8 (pi)'),
('together', 'Qwen/Qwen3.6-Plus', 'Qwen/Qwen3.6 Plus (pi)'),
('together', 'deepseek-ai/DeepSeek-V3', 'Deepseek Ai/Deepseek V3 (pi)'),
('together', 'deepseek-ai/DeepSeek-V3-1', 'Deepseek Ai/Deepseek V3 1 (pi)'),
('together', 'deepseek-ai/DeepSeek-V4-Pro', 'Deepseek Ai/Deepseek V4 Pro (pi)'),
('together', 'essentialai/Rnj-1-Instruct', 'Essentialai/Rnj 1 Instruct (pi)'),
('together', 'google/gemma-4-31B-it', 'Google/Gemma 4 31B It (pi)'),
('together', 'zai-org/GLM-5.1', 'Zai Org/Glm 5.1 (pi)'),
('vercel-ai-gateway', 'alibaba/qwen-3-14b', 'Alibaba/Qwen 3 14B (pi)'),
('vercel-ai-gateway', 'alibaba/qwen-3-30b', 'Alibaba/Qwen 3 30B (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3-coder', 'Alibaba/Qwen3 Coder (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3-coder-30b-a3b', 'Alibaba/Qwen3 Coder 30B A3B (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3-coder-plus', 'Alibaba/Qwen3 Coder Plus (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3-vl-thinking', 'Alibaba/Qwen3 Vl Thinking (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3.5-flash', 'Alibaba/Qwen3.5 Flash (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3.5-plus', 'Alibaba/Qwen3.5 Plus (pi)'),
('vercel-ai-gateway', 'alibaba/qwen3.6-plus', 'Alibaba/Qwen3.6 Plus (pi)'),
('vercel-ai-gateway', 'anthropic/claude-3-haiku', 'Anthropic/Claude 3 Haiku (pi)'),
('vercel-ai-gateway', 'anthropic/claude-3.5-haiku', 'Anthropic/Claude 3.5 Haiku (pi)'),
('vercel-ai-gateway', 'anthropic/claude-haiku-4.5', 'Anthropic/Claude Haiku 4.5 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-opus-4', 'Anthropic/Claude Opus 4 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-opus-4.1', 'Anthropic/Claude Opus 4.1 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-opus-4.5', 'Anthropic/Claude Opus 4.5 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-opus-4.6', 'Anthropic/Claude Opus 4.6 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-sonnet-4', 'Anthropic/Claude Sonnet 4 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-sonnet-4.5', 'Anthropic/Claude Sonnet 4.5 (pi)'),
('vercel-ai-gateway', 'anthropic/claude-sonnet-4.6', 'Anthropic/Claude Sonnet 4.6 (pi)'),
('vercel-ai-gateway', 'arcee-ai/trinity-large-preview', 'Arcee Ai/Trinity Large Preview (pi)'),
('vercel-ai-gateway', 'arcee-ai/trinity-large-thinking', 'Arcee Ai/Trinity Large Thinking (pi)'),
('vercel-ai-gateway', 'bytedance/seed-1.6', 'Bytedance/Seed 1.6 (pi)'),
('vercel-ai-gateway', 'cohere/command-a', 'Cohere/Command A (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-r1', 'Deepseek/Deepseek R1 (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-v3', 'Deepseek/Deepseek V3 (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-v3.1', 'Deepseek/Deepseek V3.1 (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-v3.1-terminus', 'Deepseek/Deepseek V3.1 Terminus (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-v4-flash', 'Deepseek/Deepseek V4 Flash (pi)'),
('vercel-ai-gateway', 'deepseek/deepseek-v4-pro', 'Deepseek/Deepseek V4 Pro (pi)'),
('vercel-ai-gateway', 'google/gemini-3-flash', 'Google/Gemini 3 Flash (pi)'),
('vercel-ai-gateway', 'google/gemini-3-pro-preview', 'Google/Gemini 3 Pro Preview (pi)'),
('vercel-ai-gateway', 'google/gemini-3.1-flash-lite', 'Google/Gemini 3.1 Flash Lite (pi)'),
('vercel-ai-gateway', 'google/gemini-3.1-flash-lite-preview', 'Google/Gemini 3.1 Flash Lite Preview (pi)'),
('vercel-ai-gateway', 'google/gemini-3.1-pro-preview', 'Google/Gemini 3.1 Pro Preview (pi)'),
('vercel-ai-gateway', 'google/gemini-3.5-flash', 'Google/Gemini 3.5 Flash (pi)'),
('vercel-ai-gateway', 'google/gemma-4-31b-it', 'Google/Gemma 4 31B It (pi)'),
('vercel-ai-gateway', 'inception/mercury-coder-small', 'Inception/Mercury Coder Small (pi)'),
('vercel-ai-gateway', 'meituan/longcat-flash-chat', 'Meituan/Longcat Flash Chat (pi)'),
('vercel-ai-gateway', 'meta/llama-3.1-8b', 'Meta/Llama 3.1 8B (pi)'),
('vercel-ai-gateway', 'meta/llama-4-maverick', 'Meta/Llama 4 Maverick (pi)'),
('vercel-ai-gateway', 'meta/llama-4-scout', 'Meta/Llama 4 Scout (pi)'),
('vercel-ai-gateway', 'mistral/codestral', 'Mistral/Codestral (pi)'),
('vercel-ai-gateway', 'mistral/devstral-small', 'Mistral/Devstral Small (pi)'),
('vercel-ai-gateway', 'mistral/ministral-3b', 'Mistral/Ministral 3B (pi)'),
('vercel-ai-gateway', 'mistral/ministral-8b', 'Mistral/Ministral 8B (pi)'),
('vercel-ai-gateway', 'mistral/mistral-medium', 'Mistral/Mistral Medium (pi)'),
('vercel-ai-gateway', 'mistral/mistral-medium-3.5', 'Mistral/Mistral Medium 3.5 (pi)'),
('vercel-ai-gateway', 'mistral/mistral-small', 'Mistral/Mistral Small (pi)'),
('vercel-ai-gateway', 'openai/gpt-4-turbo', 'Openai/Gpt 4 Turbo (pi)'),
('vercel-ai-gateway', 'openai/gpt-4.1', 'Openai/Gpt 4.1 (pi)'),
('vercel-ai-gateway', 'openai/gpt-4.1-mini', 'Openai/Gpt 4.1 Mini (pi)'),
('vercel-ai-gateway', 'openai/gpt-4.1-nano', 'Openai/Gpt 4.1 Nano (pi)'),
('vercel-ai-gateway', 'openai/gpt-4o', 'Openai/Gpt 4O (pi)'),
('vercel-ai-gateway', 'openai/gpt-4o-mini', 'Openai/Gpt 4O Mini (pi)'),
('vercel-ai-gateway', 'openai/gpt-5', 'Openai/Gpt 5 (pi)'),
('vercel-ai-gateway', 'openai/gpt-5-chat', 'Openai/Gpt 5 Chat (pi)'),
('vercel-ai-gateway', 'openai/gpt-5-mini', 'Openai/Gpt 5 Mini (pi)'),
('vercel-ai-gateway', 'openai/gpt-5-nano', 'Openai/Gpt 5 Nano (pi)'),
('vercel-ai-gateway', 'openai/gpt-5-pro', 'Openai/Gpt 5 Pro (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.1-instant', 'Openai/Gpt 5.1 Instant (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.1-thinking', 'Openai/Gpt 5.1 Thinking (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.3-chat', 'Openai/Gpt 5.3 Chat (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.4', 'Openai/Gpt 5.4 (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.4-mini', 'Openai/Gpt 5.4 Mini (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.4-nano', 'Openai/Gpt 5.4 Nano (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.4-pro', 'Openai/Gpt 5.4 Pro (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.5', 'Openai/Gpt 5.5 (pi)'),
('vercel-ai-gateway', 'openai/gpt-5.5-pro', 'Openai/Gpt 5.5 Pro (pi)'),
('vercel-ai-gateway', 'openai/o1', 'Openai/O1 (pi)'),
('vercel-ai-gateway', 'openai/o3', 'Openai/O3 (pi)'),
('vercel-ai-gateway', 'openai/o3-deep-research', 'Openai/O3 Deep Research (pi)'),
('vercel-ai-gateway', 'openai/o3-mini', 'Openai/O3 Mini (pi)'),
('vercel-ai-gateway', 'openai/o3-pro', 'Openai/O3 Pro (pi)'),
('vercel-ai-gateway', 'openai/o4-mini', 'Openai/O4 Mini (pi)'),
('vercel-ai-gateway', 'zai/glm-4.5', 'Zai/Glm 4.5 (pi)'),
('vercel-ai-gateway', 'zai/glm-4.5-air', 'Zai/Glm 4.5 Air (pi)'),
('vercel-ai-gateway', 'zai/glm-4.5v', 'Zai/Glm 4.5V (pi)'),
('vercel-ai-gateway', 'zai/glm-4.6', 'Zai/Glm 4.6 (pi)'),
('vercel-ai-gateway', 'zai/glm-4.6v', 'Zai/Glm 4.6V (pi)'),
('vercel-ai-gateway', 'zai/glm-4.6v-flash', 'Zai/Glm 4.6V Flash (pi)'),
('vercel-ai-gateway', 'zai/glm-5', 'Zai/Glm 5 (pi)'),
('vercel-ai-gateway', 'zai/glm-5-turbo', 'Zai/Glm 5 Turbo (pi)'),
('vercel-ai-gateway', 'zai/glm-5.1', 'Zai/Glm 5.1 (pi)'),
('vercel-ai-gateway', 'zai/glm-5v-turbo', 'Zai/Glm 5V Turbo (pi)'),
('xai', 'grok-3-fast', 'Grok 3 Fast (pi)'),
('xai', 'grok-4.3', 'Grok 4.3 (pi)'),
('xai', 'grok-build-0.1', 'Grok Build 0.1 (pi)'),
('xai', 'grok-code-fast-1', 'Grok Code Fast 1 (pi)');
